---
title: "WKEELMIGRATION CLOSURE DATA TREATMENT"
author: "Michael Pedersen, Argyrios Sapounidis, Caroline Durif, Matthew Gollock, Derek Evans, Cédric Briand"
date: "january 2020"
output: 
  html_document:
    keep_md: true
---

```{r launch, echo=FALSE, include=FALSE}
require(knitr)
opts_knit$set(eval.after = 'fig.cap') # to be used in chunks used only to plot pictures
knitr::opts_chunk$set(echo=FALSE)
options(knitr.table.format = 'html') # options pour kable
options(knitr.kable.NA = '.')
setwd("C:\\workspace\\gitwgeel\\Misc\\wkeelmigration\\")
source("..\\..\\R\\utilities\\load_library.R")
source("functions.R")
load_package("readxl")
load_package("stringr")
load_package("pool")
load_package("DBI")
load_package("RPostgreSQL")
load_package("glue")
load_package("sqldf")
load_package("tidyverse")
load_package("ggforce") # better circular plots using ggplot
load_package("printr")
load_package("kableExtra")

source("..\\..\\R\\shiny_data_integration\\shiny_di\\loading_functions.R")
source("..\\..\\R\\shiny_data_integration\\shiny_di\\database_reference.R") # extract_ref
load(file=str_c("C:\\workspace\\gitwgeel\\R\\shiny_data_integration\\shiny_di","\\common\\data\\init_data.Rdata"))  
datawd <- "C:\\Users\\cedric.briand\\OneDrive - EPTB Vilaine\\Projets\\GRISAM\\2020\\wkeemigration\\source\\"
datawd1 <- "C:\\Users\\cedric.briand\\OneDrive - EPTB Vilaine\\Projets\\GRISAM\\2020\\wkeemigration\\Treated closure\\"

imgwd <- "C:\\workspace\\wgeeldata\\wkeelmigration\\image\\"

library("sf")
library("ggspatial")

dsn <-  paste0("PG:dbname='wgeel' host='localhost' port ='5436'",
		" user='", userlocal,
		"' password='", passwordlocal,"'")
```

# preparing the files

see readme.md in this folder for notes on source file.


# reading the files


```{r readfiles, echo=FALSE, include=FALSE, eval=FALSE}
fcl <- list.files(datawd1,pattern='.xlsx')
load( file=str_c(datawd,"saved_data.Rdata"))
load(file=str_c(datawd,"cou.Rdata"))

datasource <- "wkeelmigration"
list_closure <- list()
for (f in fcl){
	# f <- fcl[1]
	path <- str_c(datawd1,f)	
	file<-basename(path)
	mylocalfilename<-gsub(".xlsx","",file)
	country <- substring(mylocalfilename,1,2)
	cat(country)
	list_closure[[mylocalfilename]] <-	load_closures(path, datasource)
}
save(list_closure,file=str_c(datawd1,"list_closure.Rdata"))
```

```{r quality_analysis, echo=TRUE, include=TRUE}
load(file=str_c(datawd1,"list_closure.Rdata"))
# list_closure is a list with all data sets (readme, data, series) as elements of the list
# below we extract the list of data and bind them all in a single data.frame
# to do so, I had to constrain the column type during file reading (see functions.R)
res <- map(list_closure,function(X){			X[["data"]]		}) %>% 
		bind_rows()
Hmisc::describe(res) %>% html()

# these are all empty lines ....
# print(res[is.na(res$eel_emu_nameshort),],n=2)
# all NA print(res[is.na(res$eel_emu_nameshort),],n=1000)
res <- res[!is.na(res$eel_emu_nameshort),]
# describe file again

# treating month

unique(res$eel_month)
res$eel_month <- tolower(res$eel_month)
# resm<-res[is.na(res$eel_month),]
res$eel_month[is.na(res$eel_month)]<-"whole year"
# removing whole year and missing year
res$eel_month[res$eel_month=="abr"] <- "apr"
res$eel_month[res$eel_month=="ago"] <- "aug"




# recode the month
res$eel_month <- recode(res$eel_month, 
    "whole year"=13,
    "jan"=1, 
		"feb"=2,
		"mar"=3, 
		"apr"=4, 
		"may"=5, 
		"jun"=6,
		"jul"=7,
		"aug"=8,
		"sep"=9,
		"oct"=10,
		"nov"=11,
		"dec"=12)
Hmisc::describe(as.factor(res$eel_month)) %>% html
# number of data per emu
#res %>% mutate("freq"=1) %>% filter(eel_year>2000 & eel_year<2019) %>%
#xtabs ( formula=freq ~ eel_year + eel_month +eel_emu_nameshort)


res <- res[order(res$eel_typ_name,res$eel_emu_nameshort, res$eel_year, res$eel_month,res$eel_lfs_code,res$eel_hty_code),]
res$id <- 1:nrow(res)

# checking for duplicates; These have sereral values for one stage (means that they have more than 2 habitats types

res %>% mutate("freq"=1) %>% filter(eel_year>2000 & eel_year<2019) %>%
		xtabs ( formula=freq ~ eel_typ_name + eel_year + eel_month +eel_emu_nameshort +eel_lfs_code)%>%
		as.data.frame() %>% filter(Freq>2)%>% kable()%>% kable_styling() %>%
		scroll_box(width = "500px", height = "200px")

# temporarily dropping those files
# res <-res%>%filter(!eel_emu_nameshort%in% c('PL_Oder','PL_Vist'))

# SEARCHING FOR DUPLICATES-----------------------------------------------------------

duplicates <- res %>% mutate("freq"=1) %>% filter(eel_year>2000 & eel_year<2019) %>%
		xtabs ( formula=freq ~ eel_year + eel_month +eel_emu_nameshort +eel_lfs_code+eel_hty_code+eel_typ_name)%>%
		as.data.frame() %>% filter(Freq>1)

kable(duplicates)%>% kable_styling() %>%
		scroll_box(width = "500px", height = "200px")


colnames(res) <-gsub("eel_","",colnames(res))



# mycolumn="hty_code";mydata=res
nicetable <- function(mydata, mycolumn,t=TRUE){
  if (t){
  ta <- table(mydata[,mycolumn]) %>% t()
  } else {
   ta <- as.data.frame(table(mydata[,mycolumn])) 
  }
  kable(ta)
}
nicetable(res,"fishery_closure_type")%>%
  kable_styling(c("striped", "bordered"))
nicetable(res,"emu_nameshort", t=FALSE)
nicetable(res,"month")%>%
  kable_styling(c("striped", "bordered"))
nicetable(res,"hty_code")%>%
  kable_styling(c("striped", "bordered"))
describe(res$fishery_closure_percent)%>%html()



save(res,file=str_c(datawd1,"res_closure.Rdata"))
```


```{r tables, echo=TRUE, include=TRUE, eval=TRUE}
load(file=str_c(datawd1,"res_closure.Rdata"))

#  before correction this table had a lot of values in red (duplicates)
res %>%	group_by(typ_name, emu_nameshort,lfs_code,hty_code,year,month) %>%
		summarize(N=n()) %>% 
		mutate(N = cell_spec(N, "html", color = ifelse(N > 1, "red", "black"),bold=ifelse(N > 1, T, F)))%>%
		pivot_wider(names_from="month",values_from="N")%>%
		kable(escape = F, align = "c") %>%
		kable_styling(c("striped", "condensed"), full_width = F)%>%
		scroll_box(width = "600px", height = "400px")


```


```{r pivot_tables, echo=TRUE, include=TRUE, eval=TRUE}
load(file=str_c(datawd1,"res_closure.Rdata"))


#  before correction this table had a lot of values in red (duplicates)
# comment and reason for closure take first
res %>%	
  mutate(fishery_closure_type=ifelse(is.na(fishery_closure_type),"0",fishery_closure_type),
         reason_for_closure=ifelse(is.na(reason_for_closure),"",reason_for_closure),
         comment=ifelse(is.na(comment),"",comment))%>% # remove NA from fishery closure type
  group_by(typ_name, emu_nameshort,lfs_code,hty_code,year,month) %>%
  summarize(duplicate=n(), 
			fishery_closure_percent=sum(fishery_closure_percent), 
			fishery_closure_type=paste0(fishery_closure_type, collapse = "+"), 
			reason_for_closure = first(reason_for_closure),  
			comment = first(comment)) %>%
  mutate(duplicate=cell_spec(duplicate,, "html",color=spec_color(duplicate)),
			fishery_closure_percent = 
           case_when(fishery_closure_type=='PS'  ~ cell_spec(fishery_closure_percent, "html",
                                                             color ="white",
                                                             background = "red",
                                                             link = "#",
                                                             tooltip =paste0("reason:",reason_for_closure, "Comment: ", comment )),
                     fishery_closure_type=='PT' ~ cell_spec(fishery_closure_percent, "html",
                                                             color ="white",
                                                             background = "blue",
                                                            link = "#",
                                                            tooltip =paste0("reason:",reason_for_closure, "Comment: ", comment )),
                     fishery_closure_type=='PST' ~ cell_spec(fishery_closure_percent, "html",
                                                              color ="white",
                                                             background = "purple",
                                                             link = "#",
                                                             tooltip =paste0("reason:",reason_for_closure, "Comment: ", comment )),
                     fishery_closure_type=='T' ~ cell_spec(fishery_closure_percent, "html",
                                                            color ="white",
                                                             background = "black",
                                                           link = "#",
                                                           tooltip =paste0("reason:",reason_for_closure, "Comment: ", comment ))
           ))%>%
  select(duplicate,typ_name, emu_nameshort,lfs_code,hty_code,year,month, fishery_closure_percent) %>%
  pivot_wider(names_from="month",values_from="fishery_closure_percent")%>%
  kable(escape = F, align = "c") %>%
  kable_styling(c("striped", "condensed"), full_width = F)%>%
  scroll_box(width = "600px", height = "400px")


```




Empty graphs correspond to all zero values reported for one year, those values are now removed

# Silver eels

```{r s, echo=FALSE, include=FALSE, eval=FALSE}



fnplot <- function(emu, lfs, hty,colfill="grey10"){
  # remove all zero values
  res1 <- res %>% 
	  anti_join(all_zero)
  # calculate sum
	res2 <-  res1 %>%
			filter(emu_nameshort==emu,
					lfs_code==lfs,
					hty_code %in% hty) %>%
			group_by(emu_nameshort,year,month)%>%
			summarize(value=sum(value))
	# calculate percentage
	res3 <- left_join (res2,					
					res2 %>% group_by(emu_nameshort,year)%>%		
							summarize(sum_per_year=sum(value,na.rm=TRUE)),
					by = c("emu_nameshort","year")) %>%	
			mutate(perc_per_month=100*value/sum_per_year) 
	options(warn=-1)
	if (nrow(res3)>1){
		
		g <- ggplot(res3,aes(x = month)) +
				geom_col(aes(y=perc_per_month),fill=colfill,color="black")+
				xlab("month")+
				ylab("percentage catch")+
				facet_wrap(~year)+
				theme_bw()+
				ggtitle(str_c("Percentage per month ",emu, " ", lfs," ",paste0(hty,collapse="+")))
		
		print(g)
	}
		options(warn=0)
}



for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'S',
			hty = c("C","TC","T"),
			emu=the_emu)
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'S',
			hty = c("F"),
			emu=the_emu, 
			colfill= "navyblue")	
}
```
<!--  -->
<!-- # Glass eel -->
<!--  -->
<!-- ```{r g, echo=TRUE, include=TRUE} -->
<!-- res %>% filter(lfs_code=="G") %>% select(hty_code) %>% distinct() -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'G', -->
<!-- 			hty = c("T"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "tomato1")	 -->
<!-- } -->
<!--  -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'G', -->
<!-- 			hty = c("F"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "violetred")	 -->
<!-- } -->
<!--  -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'G', -->
<!-- 			hty = c("FTC"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "firebrick")	 -->
<!-- } -->
<!--  -->
<!-- ``` -->
<!--  -->
<!--  -->
<!-- # Yellow -->
<!--  -->
<!-- ```{r y, echo=TRUE, include=TRUE} -->
<!-- res %>% filter(lfs_code=="Y") %>% select(hty_code) %>% distinct() -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'Y', -->
<!-- 			hty = c("C"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "green")	 -->
<!-- } -->
<!--  -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'Y', -->
<!-- 			hty = c("F"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "greenyellow")	 -->
<!-- } -->
<!--  -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'Y', -->
<!-- 			hty = c("T"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "limegreen")	 -->
<!-- } -->
<!--  -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'Y', -->
<!-- 			hty = c("MO"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "olivedrab")	 -->
<!-- } -->
<!--  -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'Y', -->
<!-- 			hty = c("FTC"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "springgreen")	 -->
<!-- } -->
<!--  -->
<!-- ``` -->
<!--  -->
<!-- # Yellow silver -->
<!--  -->
<!-- ```{r ys, echo=TRUE, include=TRUE} -->
<!-- res %>% filter(lfs_code=="YS") %>% select(hty_code) %>% distinct() -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'YS', -->
<!-- 			hty = c("C"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "plum")	 -->
<!-- } -->
<!--  -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'YS', -->
<!-- 			hty = c("F"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "purple")	 -->
<!-- } -->
<!--  -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'YS', -->
<!-- 			hty = c("T"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "magenta")	 -->
<!-- } -->
<!--  -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'YS', -->
<!-- 			hty = c("FTC"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "violet")	 -->
<!-- } -->
<!--  -->
<!-- for (the_emu in unique(res$emu_nameshort)){ -->
<!-- 	fnplot(lfs = 'YS', -->
<!-- 			hty = c("TC"), -->
<!-- 			emu=the_emu,  -->
<!-- 			colfill= "hotpink")	 -->
<!-- } -->
<!-- ``` -->