---
title: "WKEELMIGRATION LANDINGS SEASONALITY DATA TREATMENT"
author: "Cédric Briand, Jan Dag Pohlmann, Estibaliz diaz and Hilaire Drouineau, "
date: "january 2020"
output: 
  html_document:
    keep_md: true
---

```{r launch, echo=FALSE, include=FALSE}
require(knitr)
opts_knit$set(eval.after = 'fig.cap') # to be used in chunks used only to plot pictures
knitr::opts_chunk$set(echo=FALSE)
options(knitr.table.format = 'html') # options pour kable
options(knitr.kable.NA = '.')
setwd("C:\\workspace\\gitwgeel\\Misc\\wkeelmigration\\")
source("..\\..\\R\\utilities\\load_library.R")
source("functions.R")
load_package("readxl")
load_package("stringr")
load_package("pool")
load_package("DBI")
load_package("RPostgreSQL")
load_package("glue")
load_package("sqldf")
load_package("tidyverse")
load_package("ggforce") # better circular plots using ggplot
load_package("printr")
load_package("kableExtra")

source("..\\..\\R\\shiny_data_integration\\shiny_di\\loading_functions.R")
source("..\\..\\R\\shiny_data_integration\\shiny_di\\database_reference.R") # extract_ref
load(file=str_c("C:\\workspace\\gitwgeel\\R\\shiny_data_integration\\shiny_di","\\common\\data\\init_data.Rdata"))  
datawd <- "C:\\Users\\cedric.briand\\OneDrive - EPTB Vilaine\\Projets\\GRISAM\\2020\\wkeemigration\\source\\"
datawd1 <- "C:\\Users\\cedric.briand\\OneDrive - EPTB Vilaine\\Projets\\GRISAM\\2020\\wkeemigration\\Treated commercial\\"

imgwd <- "C:\\workspace\\wgeeldata\\wkeelmigration\\image\\"

library("sf")
library("ggspatial")

dsn <-  paste0("PG:dbname='wgeel' host='localhost' port ='5436'",
		" user='", userlocal,
		"' password='", passwordlocal,"'")
```

# preparing the files

see readme.md in this folder for notes on source file.


# reading the files


```{r readfiles, echo=FALSE, include=FALSE, eval=FALSE}
fcl <- list.files(datawd1,pattern='commercial_landings')
load( file=str_c(datawd,"saved_data.Rdata"))
load(file=str_c(datawd,"cou.Rdata"))

datasource <- "wkeelmigration"
list_seasonality <- list()
for (f in fcl){
	# f <- fcl[1]
	path <- str_c(datawd1,f)	
	file<-basename(path)
	mylocalfilename<-gsub(".xlsx","",file)
	country <- substring(mylocalfilename,1,2)
	list_seasonality[[mylocalfilename]] <-	load_landings(path, datasource)
}
save(list_seasonality,file=str_c(datawd1,"list_seasonality.Rdata"))
```

```{r quality_analysis, echo=TRUE, include=TRUE}
load(file=str_c(datawd1,"list_seasonality.Rdata"))
# list_seasonality is a list with all data sets (readme, data, series) as elements of the list
# below we extract the list of data and bind them all in a single data.frame
# to do so, I had to constrain the column type during file reading (see functions.R)
res <- map(list_seasonality,function(X){			X[["data"]]		}) %>% 
		bind_rows()
Hmisc::describe(res)

# these are all empty lines ....
# print(res[is.na(res$eel_emu_nameshort),],n=2)
# all NA print(res[is.na(res$eel_emu_nameshort),],n=1000)
res <- res[!is.na(res$eel_emu_nameshort),]
# describe file again
Hmisc::describe(res)
# All ND, NP or NM
print(res[is.na(res$eel_value),],n=40)
# removing those rows
res <- res[!is.na(res$eel_value),]
nrow(res) 

unique(res$eel_month)
res$eel_month <- tolower(res$eel_month)
# removing whole year and missing year
resw <- res[res$eel_month%in%c("whole year"),]
print(resw)
# ONLY GB_Neag and this is whole_year not remain year
resr <- res[res$eel_month%in%c("remain year"),]
print(resr)
res <-res[!res$eel_month%in%c("whole year", "remain year"),]
# recode the month
res$eel_month <- recode(res$eel_month, 
		"mar"=3, 
		"apr"=4, 
		"may"=5, 
		"jun"=6,
		"jul"=7,
		"aug"=8,
		"sep"=9,
		"oct"=10,
		"nov"=11,
		"dec"=12, 
		"jan"=1, 
		"feb"=2
)
Hmisc::describe(res$eel_month)
# number of data per emu
#res %>% mutate("freq"=1) %>% filter(eel_year>2000 & eel_year<2019) %>%
#xtabs ( formula=freq ~ eel_year + eel_month +eel_emu_nameshort)


res <- res[order(res$eel_typ_name,res$eel_emu_nameshort, res$eel_year, res$eel_month,res$eel_lfs_code,res$eel_hty_code),]
res$id <- 1:nrow(res)

# some of the data have more than two rows per month per year, it's OK for germany but there is a problem with the
# Polish file
res %>% mutate("freq"=1) %>% filter(eel_year>2000 & eel_year<2019) %>%
		xtabs ( formula=freq ~ eel_year + eel_month +eel_emu_nameshort +eel_lfs_code)%>%
		as.data.frame() %>% filter(Freq>2)%>% kable()%>% kable_styling() %>%
		scroll_box(width = "500px", height = "200px")

# temporarily dropping those files
res <-res%>%filter(!eel_emu_nameshort%in% c('PL_Oder','PL_Vist'))

# SEARCHING FOR DUPLICATES-----------------------------------------------------------

duplicates <- res %>% mutate("freq"=1) %>% filter(eel_year>2000 & eel_year<2019) %>%
		xtabs ( formula=freq ~ eel_year + eel_month +eel_emu_nameshort +eel_lfs_code+eel_hty_code+eel_typ_name)%>%
		as.data.frame() %>% filter(Freq>1)

kable(duplicates)%>% kable_styling() %>%
		scroll_box(width = "500px", height = "200px")

# =>DUPLICATED VALUES SENT TO ESTI ...

colnames(res) <-gsub("eel_","",colnames(res))


# COMMERCIAL AND RECREATIONAL -----------------------------------------------------------

# The only recreational landings there are the boat fishery for glass eel in Spain
# I'm not using the type, we'll work with both commercial and recreational as a single category.

res %>% filter(typ_name=="rec_landings_kg") %>% select(emu_nameshort) %>% distinct()




unique(res$emu_nameshort)

unique(res$hty_code)
table(res$hty_code)
# there are only three lines with hty code 'FT' in Ireland, I'm correcting them to F
res$hty_code[res$hty_code=='FT'] <- 'F'

# Now I don't remember why we put this  :it's fortunate that we don't use that in a dabase. 
# How will we ever treat those categories ?
# "FTC" "FT"  "TC" 

unique(res$lfs_code) # OK
save(res,file=str_c(datawd,"res_landings.Rdata"))
```


```{r tables, echo=TRUE, include=TRUE}
load(file=str_c(datawd,"res_landings.Rdata"))
res %>%	group_by(emu_nameshort,lfs_code,hty_code,year,month) %>%
		summarize(N=n()) %>% 
		mutate(N = cell_spec(N, "html", color = ifelse(N > 1, "red", "black"),bold=ifelse(N > 1, T, F)))%>%
		pivot_wider(names_from="month",values_from="N")%>%
		kable(escape = F, align = "c") %>%
		kable_styling(c("striped", "condensed"), full_width = F)%>%
		scroll_box(width = "600px", height = "400px")




```



# Silver eels

```{r s, echo=TRUE, include=TRUE}



fnplot <- function(emu, lfs, hty,colfill="grey10"){
	res2 <- res %>% 
			filter(emu_nameshort==emu,
					lfs_code==lfs,
					hty_code %in% hty) %>%
			group_by(emu_nameshort,year,month)%>%
			summarize(value=sum(value))
	
	res3 <- left_join (res2,					
					res2 %>% group_by(emu_nameshort,year)%>%		
							summarize(sum_per_year=sum(value,na.rm=TRUE)),
					by = c("emu_nameshort","year")) %>%	
			mutate(perc_per_month=100*value/sum_per_year) 
	
	if (nrow(res3)>1){
		
		g <- ggplot(res3,aes(x = month)) +
				geom_col(aes(y=perc_per_month),fill=colfill,color="black")+
				xlab("month")+
				ylab("percentage catch")+
				facet_wrap(~year)+
				theme_bw()+
				ggtitle(str_c("Percentage per month ",emu, " ", lfs," ",paste0(hty,collapse="+")))
		
		print(g)
	}
}



for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'S',
			hty = c("C","TC","T"),
			emu=the_emu)
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'S',
			hty = c("F"),
			emu=the_emu, 
			colfill= "navyblue")	
}
```

# Glass eel

```{r g, echo=TRUE, include=TRUE}
res %>% filter(lfs_code=="G") %>% select(hty_code) %>% distinct()
for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'G',
			hty = c("T"),
			emu=the_emu, 
			colfill= "tomato1")	
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'G',
			hty = c("F"),
			emu=the_emu, 
			colfill= "violetred")	
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'G',
			hty = c("FTC"),
			emu=the_emu, 
			colfill= "firebrick")	
}

```


# Yellow

```{r y, echo=TRUE, include=TRUE}
res %>% filter(lfs_code=="Y") %>% select(hty_code) %>% distinct()
for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'Y',
			hty = c("C"),
			emu=the_emu, 
			colfill= "green")	
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'Y',
			hty = c("F"),
			emu=the_emu, 
			colfill= "greenyellow")	
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'Y',
			hty = c("T"),
			emu=the_emu, 
			colfill= "limegreen")	
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'Y',
			hty = c("MO"),
			emu=the_emu, 
			colfill= "olivedrab")	
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'Y',
			hty = c("FTC"),
			emu=the_emu, 
			colfill= "springgreen")	
}

```

# Yellow silver

```{r ys, echo=TRUE, include=TRUE}
res %>% filter(lfs_code=="YS") %>% select(hty_code) %>% distinct()
for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'YS',
			hty = c("C"),
			emu=the_emu, 
			colfill= "plum")	
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'YS',
			hty = c("F"),
			emu=the_emu, 
			colfill= "purple")	
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'YS',
			hty = c("T"),
			emu=the_emu, 
			colfill= "magenta")	
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'YS',
			hty = c("FTC"),
			emu=the_emu, 
			colfill= "violet")	
}

for (the_emu in unique(res$emu_nameshort)){
	fnplot(lfs = 'YS',
			hty = c("TC"),
			emu=the_emu, 
			colfill= "hotpink")	
}
```