---
title: "WKEELMIGRATION scientific litterature review"
date: "february 2020"
output: 
  html_document:
    keep_md: true
---


 
```{r launch, echo=FALSE, include=FALSE}
require(knitr)
opts_knit$set(eval.after = 'fig.cap' ) # to be used in chunks used only to plot pictures
knitr::opts_chunk$set(fig.width=12, fig.height=8, echo=FALSE)
options(knitr.table.format = 'html') # options pour kable
options(knitr.kable.NA = '.')
setwd("C:\\workspace\\gitwgeel\\Misc\\wkeelmigration\\")
source("..\\..\\R\\utilities\\load_library.R")
source("functions.R")
load_package("readxl")
load_package("stringr")
load_package("pool")
load_package("DBI")
load_package("RPostgreSQL")
load_package("glue")
load_package("sqldf")
load_package("tidyverse")
load_package("ggforce") # better circular plots using ggplot
load_package("printr")
load_package("kableExtra")
load_package("pander")
load_package("colorspace")
load_package("ggthemes")
load_package("sp")

source("..\\..\\R\\shiny_data_integration\\shiny_di\\loading_functions.R")
source("..\\..\\R\\shiny_data_integration\\shiny_di\\database_reference.R") # extract_ref
load(file=str_c("C:\\workspace\\gitwgeel\\R\\shiny_data_integration\\shiny_di","\\common\\data\\init_data.Rdata"))  
datawd <- "C:\\Users\\cedric.briand\\OneDrive - EPTB Vilaine\\Projets\\GRISAM\\2020\\wkeemigration\\source\\"

imgwd <- "C:\\workspace\\wgeeldata\\wkeelmigration\\image\\"

library("sf")
library("ggspatial")

dsn <-  paste0("PG:dbname='wgeel' host='localhost' port ='5436'",
		" user='", userlocal,
		"' password='", passwordlocal,"'")
load(file=str_c(datawd,"saved_data.Rdata"))
load(file=str_c(datawd,"cou.Rdata"))

#emu <- st_read(str_c(dsn= "PG:dbname='wgeel' host='localhost' port='5436' user='",userlocal,"' 
#						password='",passwordlocal,"'"), layer="ref.tr_emu_emu")
## This is the map of the emu
##emu_p <<- rmapshaper::ms_simplify(rgdal::readOGR(str_c(shpwd,"/","emu_polygons_4326.shp")), keep = 0.7) # a spatial object of class sp, symplified to be displayed easily
#emu_p <- rmapshaper::ms_simplify(emu$geom, keep = 0.7) # a spatial object of class sp, symplified to be displayed easily
### Is this emu$geom simplified, do we need it? 
#
## To calculate the center of the polygone, empty geom is not possible
#emu_no_empty_geom <- emu[which(!st_is_empty(emu$geom)),]
## This corresponds to the center of each emu
##emu_c <- rgdal::readOGR(str_c(shpwd,"/","emu_centre_4326.shp")) # a spatial object of class spatialpointsdataframe
#emu_c <- st_centroid(emu_no_empty_geom$geom)
#
#
#emu<- cbind(emu_no_empty_geom,st_coordinates(emu_c))
save(emu, file=str_c(datawd,"emu.Rdata"))

```



```{r load_excel, echo=FALSE, include=FALSE}
f <- "Literature_table_final.csv"
path <- str_c(datawd,f)	
file <- basename(path)
sea <- read_delim(file=path, delim=';' ,col_names = TRUE, skip=1)
save(sea, file=str_c(datawd,'sea.Rdata'))


```
```{r data_screening, echo=TRUE, include=TRUE}
load(file=str_c(datawd,'sea.Rdata'))
describe(sea)%>%html
test_float <- function(X) X%%1==0 
sea$id <- 1:nrow(sea)
# make it numeric
colmonth <- c( "Jan", "Feb","Mar","Apr" ,"May","June","July","Aug","Sept", "Oct","Nov","Dec")
colmonthnum<- match(colmonth, colnames(sea))

# turn all month in the dataset into numeric columns
sea <- cbind(sea %>% select(- colmonth),
		sea %>% select( colmonth) %>% 
				mutate_all(list(as.numeric)))
# turn to percentage
sea[sea$Author=="Acou et al., 2009",
		c( "Jan", "Feb","Mar","Apr" ,"May","June","July","Aug","Sept", "Oct","Nov","Dec")] <-
		sea[sea$Author=="Acou et al., 2009",
				c( "Jan", "Feb","Mar","Apr" ,"May","June","July","Aug","Sept", "Oct","Nov","Dec")]/100
# check if we have not rounded values
#is_quantitative <- sea %>% select( "Jan", "Feb","Mar","Apr" ,"May","June","July","Aug","Sept", "Oct","Nov","Dec") %>% 
#				mutate_all(list(as.numeric)) %>%
#				mutate_all(list(test_float)) %>%
#				mutate_all(.funs=function(X)1-as.numeric(X)) %>%
#				mutate_all(replace_na, replace = 0) %>%
#				pmap_dbl(.f=sum)>0
#sea$is_quantitative <- is_quantitative
#sum(is_quantitative) # 41
table(sea$Type)
colnames(sea) <- tolower(colnames(sea))
colnames(sea) <- make.names(colnames(sea))
sea$stage2 <- NA 
sea$stage2[grepl("G",sea$stage.)] <-'G'
sea$stage2[grepl("GE/E/Y",sea$stage.) | grepl("GE/Y",sea$stage.)|sea$stage.=="E"|sea$stage.=="E/BT"] <- "GY"
sea$stage2[grepl("S",sea$stage.)] <-'S'
sea$stage2[grepl("Y",sea$stage.)] <-'Y'
sea$stage2[grepl("BL",sea$stage.)] <-'Y'
sea$stage2[grepl("SY",sea$stage.)] <-'YS'
table(sea$stage.)
table(sea$stage2)

# data marked as "Remove" either duplicates or missing data are not integrated in the graph
# we create two sets of graphs, one for quantitative one for qualitative
table(sea$quality.of.data )
sea$isquant <- sea$quality.of.data == 'Quant'
sea$isqual <- sea$quality.of.data== 'Qual'

# Everything should be as percentages for quantitative.

sea_c <- sea[sea$isquant,]
(sss <- rowSums(sea_c[,c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec')], na.rm=TRUE ))

sea_c[sss>100,c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec')]<-	
		sea_c[sss>100,c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec')]/sss[sss>100]

(sss <- rowSums(sea_c[,c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec')], na.rm=TRUE ))

sea_c[sss<=1,c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec')]<-	
		sea_c[sss<=1,c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec')]*100

(sss <- rowSums(sea_c[,c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec')], na.rm=TRUE ))

sea_c[sss<10,c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec')]<-	
		sea_c[sss<10,c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec')]*100/sss[sss<10]

(sss <- rowSums(sea_c[,c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec')], na.rm=TRUE ))



#---------------- Quantitative data -------------------------------------------------------------------------


sea_c2 <- sea_c %>% pivot_longer(cols=c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec'),
		names_to=c("month"),values_to='freq')


sea_c2$month <- recode(sea_c2$month, 
		"jan"=1,
		"feb"=2,
		"mar"=3, 
		"apr"=4, 
		"may"=5, 
		"june"=6,
		"july"=7,
		"aug"=8,
		"sept"=9,
		"oct"=10,
		"nov"=11,
		"dec"=12
)

# data grouped per year, the average is calculated

sea_c3 <- sea_c2 %>% group_by(author,site,month,stage2, lon, lat)%>% 
		summarize(N=n(),freq=mean(freq,na.rm=TRUE)) %>%
		ungroup()
sea_c3 %>% print(n=Inf)
sea_c3 %>% filter(is.na(lon))%>%print(n=Inf)
# this site is somewhere in the UK but nothing is said in the article.... 
sea_c3[is.na(sea_c3$lon),"lon"] <- 0.47
sea_c3[is.na(sea_c3$lat),"lat"] <- 52.27 
sites <- sea_c3 %>%	select(site,lat)	 %>% distinct() %>% arrange(lat)
authors <- sea_c3 %>%	select(author,lat)	 %>% distinct() %>% arrange(lat)
sites$author=authors$author
sea_c3$site <- factor(sea_c3$site, levels=sites$site)
sea_c3$author[sea_c3$author=="Gosset et al., 2005"]<-"Gosset et al., 2005, \n Durif et al. 2003, 2008"
# first plot with all data
x11()
ggplot(sea_c3,aes(x = month)) +
		geom_col(aes(y=freq),color="black")+
		xlab("month")+
		ylab("percentage catch")+
		facet_wrap(~  stage2)



# plot for silver eels
# the facet are ordered by the order of sites (the level of the factor)
png(filename=str_c(imgwd,"Silver_quantitative_litterature.png"),width=800,height=600)
sea_c3 %>% filter(stage2=="S")%>%
		ggplot(aes(x = month)) +
		geom_col(aes(y=freq),position="dodge")+
		xlab("month")+
		ylab("percentage")+
		ylim(c(0,80))+
		scale_x_continuous(breaks = c(2,4,6,8,10)) +
		theme_igray() +
		geom_label(aes(x=5,y=70,label=author),size=3, alpha=0.5)+
		facet_wrap( ~ site)+
		theme(strip.text.x = element_text(size = 8))
		
dev.off()


# Glass eel just one series => removed and changed it to qualitative
sea_c3 %>% filter(stage2=="G")%>%
		ggplot(aes(x = month)) +
		geom_col(aes(y=freq),position="dodge")+
		xlab("month")+
		ylab("percentage catch")

# not real data for yellow eel (one series)
#sea_c3 %>% filter(stage2=="Y")%>%
#		ggplot(aes(x = month)) +
#		geom_col(aes(y=freq),position="dodge")+
#		xlab("month")+
#		ylab("percentage catch")+
#		facet_wrap( ~ site)




# qualitative data -------------------------------------------------------------------

sea_q <- sea[sea$isqual,]
nrow(sea_q)

unique(sea_q$site)
sea_q$site[sea_q$site=="Tiber  "]<-"Tiber"
sea_q$site[sea_q$site=="Salgiada  "] <- "Salgiada"

(sss <- rowSums(sea_q[,c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec')], na.rm=TRUE ))
summary(sss) # between 1 and 30 OK

# turn to long format (repeat lines for each month)
sea_q2 <- sea_q %>% pivot_longer(cols=c('jan','feb','mar','apr','may','june','july','aug','sept','oct','nov','dec'),
		names_to=c("month"),values_to='freq')

sea_q2$month <- recode(sea_q2$month, 
		"jan"=1,
		"feb"=2,
		"mar"=3, 
		"apr"=4, 
		"may"=5, 
		"june"=6,
		"july"=7,
		"aug"=8,
		"sept"=9,
		"oct"=10,
		"nov"=11,
		"dec"=12
)




options(tibble.width = Inf)
#sea_q2[is.na(sea_q2$emu),]%>%print(n=Inf) # only yellow eel OK

sea_q3G <- sea_q2 %>% 
		filter(stage2=="G"| stage2=='GY') %>%
		left_join(emu, by=c("emu"="emu_nameshort"))%>%
		group_by(author,site,month,emu,lat,lon,stage2)%>%
		summarize(N=n(),freq=round(mean(freq,na.rm=TRUE))) %>%
		ungroup()
sea_q3G$author[sea_q3G$site=="Tiber"] <- "Chiappi, 1920 & Ciccotti et al., 1995"
table(sea_q3G$author,sea_q3G$site)
sites <- sea_q3G %>%	select(site,author,  lat,lon, stage2)	 %>% distinct() %>% mutate(XY=lat+lon) %>% arrange(XY)
# my I don't see any difference between the two lines but they are still duplicated :-(
sites <- sites[!duplicated(sites$site),]

sea_q3G$site <- factor(sea_q3G$site, levels=sites$site)

# fix order
svg(filename=str_c(imgwd,"glass_qualitative_litterature.svg"),width=10,height=8)
ggplot(sea_q3G) +
		geom_tile(aes(x = month,y=site,fill=freq))+
		geom_label(aes(x=5,y=site,label=author))+
		xlab("month")+
		ylab("Intensity of migration")+	
		ggtitle("Glass eel and elver migration") +
		scale_x_continuous(breaks = c(2,4,6,8,10)) +
		scale_fill_continuous_sequential(palette = "YlOrRd")+
		facet_wrap( ~stage2) +
		theme_igray()

dev.off()



sea_q3S <- sea_q2 %>% 
		filter(stage2=="S") %>%
		group_by(author,site,month,stage2,lat,lon) %>%
		summarize(N=n(),freq=round(mean(freq,na.rm=TRUE))) %>%
		ungroup()
sea_q3S$site[is.na(sea_q3S$site)]<-""
sites <- sea_q3S %>%	select(site,author, lat,lon, stage2)	 %>% distinct()  %>% arrange(lat)

sites <- sites[!duplicated(sites$site),]
sea_q3S$site <- factor(sea_q3S$site, levels=sites$site)



svg(filename=str_c(imgwd,"silver_qualitative_litterature.svg"),width=8,height=6)
ggplot(sea_q3S) +
		geom_tile(aes(x = month,y=site,fill=freq))+
		geom_label(aes(x=5,y=site,label=author))+
		xlab("month")+
		ylab("Sites")+	
		ggtitle("Silver eel migration") +
		scale_x_continuous(breaks = c(2,4,6,8,10)) +
		scale_fill_continuous_sequential(palette = "BluYl")+
		theme_igray() +
		annotation_custom(
				grob = grid::textGrob(label = "South", hjust = 0, gp = grid::gpar(cex = 1)),
				ymin = 0,      # Vertical position of the textGrob
				ymax = 0,
				xmin = -1,         # Note: The grobs are positioned outside the plot area
				xmax = -1)
dev.off()


sea_q3Y <- sea_q2 %>% 
		filter(stage2=="Y") %>%
		group_by(author,site,month,lat,lon)%>%
		summarize(N=n(),freq=round(mean(freq,na.rm=TRUE))) %>%
		ungroup()

sites <- sea_q3Y %>%	select(site,author, lat,lon)	 %>% distinct()  %>% arrange(lat)
sea_q3Y <- sea_q3Y[!sea_q3Y$site%in%c("Umm Hufayan ","Vistula"),]
sea_q3Y$site <- factor(sea_q3Y$site, levels=sites$site)


# add author
svg(filename=str_c(imgwd,"yellow_qualitative_litterature.svg"),width=8,height=6)
ggplot(sea_q3Y) +
		geom_tile(aes(x = month,y=site,fill=freq))+
		geom_label(aes(x=5,y=site,label=author))+
		xlab("month")+
		ylab("Intensity of colonisation")+	
		ggtitle("Yellow eel colonisation") +
		scale_x_continuous(breaks = c(2,4,6,8,10)) +
		scale_fill_continuous_sequential(palette = "Terrain")+
		theme_igray()+
		theme(plot.margin=unit(c(1,1,1,3),"cm")) # top right bottom left
dev.off()




# Frémur is wrong
#sea_q3 %>% filter(stage2=="Y")%>%
#		ggplot(aes(x = month)) +
#		geom_col(aes(y=freq),position="dodge")+
#		xlab("month")+
#		ylab("percentage catch")+
#		facet_wrap( ~ site)


sea_q2 %>% filter(stage2=="S")%>%
		ggplot(aes(x = month)) +
		geom_col(aes(y=freq,fill=as.factor(site)))+
		xlab("month")+
		ylab("percentage catch")+
		facet_wrap( ~ author)








```
 