---
title: "WGEEL VS RDBES landings amounts"
date: "2026-09-23"
format: html
knitr:
  opts_chunk:
    code-fold: true
    code-line-numbers: true
    fig-align: center
    out-width: "70%"
    fig-width: 10 
    fig-asp: 0.618
---


```{r} 
#| label: R session setup
#| results: hide       # hide printed/text output
#| message: false      # hide messages
#| warning: false      # hide warnings
library(tidyverse)
library(readxl)
options(scipen=999)
```

```{r}
#| label: Load WGEEL landings data
#| results: hide       # hide printed/text output
#| message: false      # hide messages
#| warning: false      # hide warnings
load("R/shiny_data_visualisation/shiny_dv/data/ref_and_eel_data.Rdata")
source("R/shiny_data_visualisation/shiny_dv/filter_and_group_functions.R")

tb_landings_wgeel_com <- 
  filter_data("landings",
    typ = 4,
    # load all life stages
    life_stage = unique(landings$eel_lfs_code),
    # load all landings from all countries
    country = country_ref$cou_code
  ) |> 
  mutate(
    country = case_match(cou_iso3code,
      "ESP" ~ "ES",
      "IRL" ~ "IE",
      "EST" ~ "EE",
      "FIN" ~ "FI",
      "GRC" ~ "GR",
      "ITA" ~ "IT",
      "DNK" ~ "DK",
      "FRA" ~ "FR",
      "DEU" ~ "DE",
      "LTU" ~ "LT",
      "GBR" ~ "GB",
      "POL" ~ "PL",
      "SVN" ~ "SI",
      "NLD" ~ "NL",
      "ALB" ~ "AL",
      "TUR" ~ "TR",
      "LVA" ~ "LV",
      "SWE" ~ "SE",
      "HRV" ~ "HR",
      "TUN" ~ "TN",
      "PRT" ~ "PT",
      "BEL" ~ "BE",
      "MAR" ~ "MA",
      "DZA" ~ "DZ",
      "LBY" ~ "LY",
      "NOR" ~ "NO",
      "CZE" ~ "CZ",
      "MNE" ~ "ME",
      .default = cou_iso3code
    )
  )
```

```{r}
#| label: Load RDBES landings data
#| results: hide       # hide printed/text output
#| message: false      # hide messages
#| warning: false      # hide warnings
tb_landings_rdbes <- 
  readxl::read_excel("DELETE-ME-commercial_landings.xlsx") |> 
  mutate(
    mass_landed_kg = as.numeric(CLofficialWeight)
  ) 
```

```{r}
#| label: compare landings data and print results
#| message: false      # hide messages
#| warning: false      # hide warnings
#| fig-width: 10
#| fig-asp: 8
tb_landings_combined <- bind_rows(
  tb_landings_rdbes |> 
    mutate(
      source = "RDBES",
      country = recode_values(CLlandingCountry, "GB-ENG"~"GB","GB-NIR"~"GB","GB-SCT"~"GB",default = CLlandingCountry),
      year = CLyear,
      mass_landed_kg = as.numeric(CLofficialWeight)
    ),
  tb_landings_wgeel_com |> 
    filter(eel_hty_code %in% c("C","T","MO")) |> 
    mutate(
      source = "WGEEL",
      country = country,
      year = eel_year,
      mass_landed_kg = eel_value
    )  
  ) |> 
  summarise(
    .by = c(country, year, source),
    mass_landed_kg = sum(mass_landed_kg, na.rm=T)
  )

ggplot(tb_landings_combined |> filter(year %in% c(2010:2025)))+
  aes(x=country, y=mass_landed_kg, fill=source)+
  geom_col(position = "dodge",width=0.5) + 
  coord_flip()+
  facet_wrap(~year,ncol=1)+
  theme_bw()
  

```
