---
title: "Automatic tables and graphs"
author: "WGEEL"
date: "30 August 2019"
output:
  word_document
---
\newline
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings=FALSE)
setwd("C:/workspace/gitwgeel/R/Rmarkdown")
#source("R/utilities/set_directory.R")
#data_directory <- wg_choose.dir(caption = "Where do you want to save the tables and the graphs")
#data_directory <-"C:/temp"
#knitr::opts_knit$set(root.dir = data_directory)
```


## Raw landings (com and rec)
\newline

```{r load_utilities, eval=TRUE, echo=FALSE,include=FALSE}

source("../utilities/load_library.R")



#-----------------
# other libraries
#-----------------
load_package("readxl")
load_package("stringr")
load_package("reshape2")
load_package("tidyr") # unite cols in maps
load_package("rlang")
load_package("sp")
#load_package("pool")
#load_package("DBI")
load_package("RPostgreSQL")
load_package("dplyr")
load_package("RColorBrewer")
load_package("sqldf")
load_package("scales")
load_package('stringr') # text handling
#load_package("XLConnect") # for excel
load_package("ggplot2") # for excel
load_package("gridExtra")
load_package("colorspace")
load_package("ggrepel")
load_package("viridis")
load_package("svglite")
load_package("leaflet.minicharts")
load_package("glue")
load_package("kableExtra")

# load functions ------------------------------------------------------------------------------------
# retrieve reference tables needed
# the shiny is launched from shiny_data_integration/shiny thus we need the ../
if(is.null(options()$sqldf.RPostgreSQL.user)) 
source("../shiny_data_visualisation/shiny_dv/database_connection.R")
source("../shiny_data_visualisation/shiny_dv/database_reference.R")
source("../shiny_data_visualisation/shiny_dv/database_data.R")
source("../shiny_data_visualisation/shiny_dv/database_precodata.R")
source("../shiny_data_visualisation/shiny_dv/preco_diagram.R")
source("../shiny_data_visualisation/shiny_dv/graphs.R")
source("../shiny_data_visualisation/shiny_dv/maps.R")
source("../shiny_data_visualisation/shiny_dv/filter_and_group_functions.R")
source("../shiny_data_visualisation/shiny_dv/predict_missing.R")


# loading datasets 

# this file is added to the ignore list, so ask for it in your own git before launching the app
load("../shiny_data_visualisation/shiny_dv/data/maps_for_shiny.Rdata") 
#habitat_ref <- extract_ref("Habitat type")
#lfs_code_base <- extract_ref("Life stage")
##lfs_code_base <- lfs_code_base[!lfs_code_base$lfs_code %in% c("OG","QG"),]
#country_ref <- extract_ref("Country")
#country_ref <- country_ref[order(country_ref$cou_order), ]
#country_ref$cou_code <- factor(country_ref$cou_code, levels = country_ref$cou_code[order(country_ref$cou_order)], ordered = TRUE)

##have an order for the emu
#emu_ref <- extract_ref("EMU")
#emu_cou<-merge(emu_ref,country_ref,by.x="emu_cou_code",by.y="cou_code")
#emu_cou<-emu_cou[order(emu_cou$cou_order,emu_cou$emu_nameshort),]
#emu_cou<-data.frame(emu_cou,emu_order=1:nrow(emu_cou))
## Extract data from the database -------------------------------------------------------------------
#
#landings = extract_data("Landings",quality=c(1,2,4),quality_check=TRUE)
#aquaculture = extract_data("Aquaculture",quality=c(1,2,4),quality_check=TRUE)
#release = extract_data("Release",quality=c(1,2,4),quality_check=TRUE)
# this file is added to the ignore list, so ask for it in your own git before launching the app
load("../shiny_data_visualisation/shiny_dv/data/maps_for_shiny.Rdata") 
# now data are generated by the script load_data_from_the_database.R
load("../shiny_data_visualisation/shiny_dv/data/ref_and_eel_data.Rdata")
## Download the colors by country

values=c(RColorBrewer::brewer.pal(12,"Set3"),
    RColorBrewer::brewer.pal(12, "Paired"), 
    RColorBrewer::brewer.pal(8,"Accent"),
    RColorBrewer::brewer.pal(8, "Dark2"))
color_countries = setNames(values,country_ref$cou_code)

```


```{r com_land_Gt,echo=FALSE, warning=FALSE}

##raw commercial landings for Glass eel and every country
landings2<-landings[landings$eel_lfs_code=="G" & landings$eel_typ_id==4,]
year<-unique(landings2$eel_year)
country<-unique(landings2$eel_cou_code)
country<-country[country!="IE"]
hty<-unique(landings2$eel_hty_code)
filtered_data<-filter_data("landings2",
              typ = 4,
             life_stage = "G", 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)
fun.agg<-function(X){if(length(X)>0){round(sum(X)/1000,ifelse(sum(X)>1000,0,3))}else{sum(c(X,NA))}}

##table
table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
              table<-data.frame(table,sum=rowSums(table[,-1],na.rm=T))

              
              #ordering the column accordign to country order
              country_to_order = names(table)[-1]
              n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
              n_order <- n_order+1
              n_order <- c(1,n_order)
             table = table[, n_order]
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tableComLandG<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 1: Raw commercial landings (tonnes) for glass eels ","(",min(year),"-",max(year),")", "for", paste(paste(country,collapse=","),".", sep="")))

```

\newline

```{r com_land_Gf,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 1: Commercial landings per country, stage = G and habitat = T+F+C+MO.", fig.height=5, fig.width=10}

##Graph
landings3<-grouped_data
landings3$eel_value <- as.numeric(landings3$eel_value) / 1000
landings3$eel_cou_code = as.factor(landings3$eel_cou_code)
landings3$eel_cou_code<-factor(landings3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
title <- paste("Commercial landings per country,", "stage = G", "and habitat =", paste(hty,collapse="+"))

g_raw_Clandings_G<- ggplot(landings3) + geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code), position='stack')+
        ggtitle(title) + xlab("year") + ylab("Landings (tonnes)")+
        scale_fill_manual("Country",values=color_countries)+
        theme_bw()
print(g_raw_Clandings_G)

```

\newline

```{r raw_com_land_YSt, echo=FALSE, warning=FALSE}

##raw  com landings for Y S and YS for all the countries
landings2<-landings[landings$eel_lfs_code %in% c("Y","S","YS") & landings$eel_typ_id==4,]
year<-unique(landings2$eel_year)
country<-unique(landings2$eel_cou_code)
hty<-unique(landings2$eel_hty_code)
filtered_data<-filter_data("landings2",
              typ = 4,
             life_stage = c("Y","S","YS"), 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)

##table
fun.agg<-function(X){if(length(X)>0){round(sum(X)/1000,ifelse(sum(X)>1000,0,3))}else{sum(c(X,NA))}}

table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
              table<-data.frame(table,sum=rowSums(table[,-1],na.rm=T))

              
              #ordering the column accordign to country order
              country_to_order = names(table)[-1]
              n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
              n_order <- n_order+1
              n_order <- c(1,n_order)
             table = table[, n_order]
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tableComLandYS<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 2: Raw commercial landings (tonnes) for yellow and silver eels " ,"(",min(year),"-",max(year),")", "for",paste(paste(country,collapse=","), ".", sep="")))


```

\newline

```{r raw_com_land_YSf, echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 2: Commercial landings per country, stage = Y, S and YS and habitat = F+C+T+NA+MO+AL.", fig.height=5, fig.width=10}

## Graph
landings3<-grouped_data
landings3$eel_value <- as.numeric(landings3$eel_value) / 1000
landings3$eel_cou_code = as.factor(landings3$eel_cou_code)
landings3$eel_cou_code<-factor(landings3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
title <- paste("Commercial landings per country,", "stage = Y, S and YS", "and habitat =", paste(hty,collapse="+"))

g_raw_Clandings_YS<- ggplot(landings3) + geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code), position='stack')+
        ggtitle(title) + xlab("year") + ylab("Landings (tonnes)")+
        scale_fill_manual("Country",values=color_countries)+
        theme_bw()
print(g_raw_Clandings_YS)
```

\newline

```{r recLand_Y_St,echo=FALSE, warning=FALSE}

##Table raw rec landings for Y S and YS for all the countries
landings2<-landings[landings$eel_lfs_code %in% c("Y","S","YS") & landings$eel_typ_id==6,]
year<-unique(landings2$eel_year)
country<-unique(landings2$eel_cou_code)
hty<-unique(landings2$eel_hty_code)
filtered_data<-filter_data("landings2",
              typ = 6,
             life_stage = c("Y","S","YS"), 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)

##Table
fun.agg<-function(X){if(length(X)>0){round(sum(X)/1000,ifelse(sum(X)>1000,0,3))}else{sum(c(X,NA))}}

table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
              table<-data.frame(table,sum=rowSums(table[,-1],na.rm=T))

              
              #ordering the column accordign to country order
              country_to_order = names(table)[-1]
              n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
              n_order <- n_order+1
              n_order <- c(1,n_order)
             table = table[, n_order]
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tableRecLandYS<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 3: Raw recreational landings (tonnes) for yellow and silver eels  ","(",min(year),"-",max(year),")","for",paste(paste(country,collapse=","), ".", sep="")))
```

\newline

```{r recLand_Y_Sf,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 3: Recreational landings per country, stage = G and habitat = F+C+T+MO.", fig.height=5, fig.width=10}

##Graph
landings3<-grouped_data
landings3$eel_value <- as.numeric(landings3$eel_value) / 1000
landings3$eel_cou_code = as.factor(landings3$eel_cou_code)
landings3$eel_cou_code<-factor(landings3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
title <- paste("Recreational landings per country,", "stage = G ", "and habitat =", paste(hty,collapse="+"))

g_raw_Rlandings_G<- ggplot(landings3) + geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code), position='stack')+
        ggtitle(title) + xlab("year") + ylab("Landings (tonnes)")+
        scale_fill_manual("Country",values=color_countries)+
        theme_bw()
print(g_raw_Rlandings_G)


```

\newline

```{r recLand_G,echo=FALSE, warning=FALSE}

##Table raw rec landings for G for all the countries
landings2<-landings[landings$eel_lfs_code=="G" & landings$eel_typ_id==6,]
year<-unique(landings2$eel_year)
country<-unique(landings2$eel_cou_code)
hty<-unique(landings2$eel_hty_code)
filtered_data<-filter_data("landings2",
              typ = 6,
             life_stage = "G", 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)

##Table
fun.agg<-function(X){if(length(X)>0){round(sum(X)/1000,ifelse(sum(X)>1000,0,3))}else{sum(c(X,NA))}}

table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
              table<-data.frame(table,sum=rowSums(table[,-1],na.rm=T))

              
              #ordering the column accordign to country order
              country_to_order = names(table)[-1]
              n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
              n_order <- n_order+1
              n_order <- c(1,n_order)
             table = table[, n_order]
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tablerecLandG<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 4: Raw recreational landings (tonnes) for yellow and silver eels  ","(",min(year),"-",max(year),")"," for ",paste(paste(country,collapse=","), ".", sep="")))
```

\newline

```{r recLand_Gf,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 4: Recreational landings per country,stage = Y, S and YS and habitat = T,C,MO+F.", fig.height=5, fig.width=10}

## Graph
landings3<-grouped_data
landings3$eel_value <- as.numeric(landings3$eel_value) / 1000
landings3$eel_cou_code = as.factor(landings3$eel_cou_code)
landings3$eel_cou_code<-factor(landings3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
title <- paste("Recreational landings per country,", "stage = Y, S and YS", "and habitat =", paste(hty,collapse="+"))

g_raw_Rlandings_YS <- ggplot(landings3) + geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code), position='stack')+
        ggtitle(title) + xlab("year") + ylab("Landings (tonnes)")+
        scale_fill_manual("Country",values=color_countries)+
        theme_bw()
print(g_raw_Rlandings_YS)

```
\newline


## Aquaculture
\newline

```{r aquat,echo=FALSE, warning=FALSE}

##Table aquaculture for all the countries
aquaculture2<-aquaculture[aquaculture$eel_typ_id==11,]
year<-unique(aquaculture2$eel_year)
lfs<-unique(aquaculture2$eel_lfs_code)
country<-unique(aquaculture2$eel_cou_code)
hty<-unique(aquaculture2$eel_hty_code)
filtered_data<-filter_data("aquaculture2",
              typ = 11,
             life_stage = lfs, 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)

##Table
fun.agg<-function(X){if(length(X)>0){round(sum(X)/1000,ifelse(sum(X)>1000,0,3))}else{sum(c(X,NA))}}

table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
              table<-data.frame(table,sum=rowSums(table[,-1],na.rm=T))

              
              #ordering the column accordign to country order
              country_to_order = names(table)[-1]
              n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
              n_order <- n_order+1
              n_order <- c(1,n_order)
             table = table[, n_order]
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tableAqua<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 5: Aquaculture (tonnes)  ","(",min(year),"-",max(year),")"," for ",paste(paste(country,collapse=","), ".", sep="")))

```

\newline

```{r aquaf,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 5: Aquaculture per country, all stages and all habitats.", fig.height=5, fig.width=10}

## Graph
aquaculture3<-grouped_data
aquaculture3$eel_value <- as.numeric(aquaculture3$eel_value) / 1000
aquaculture3$eel_cou_code = as.factor(aquaculture3$eel_cou_code)
aquaculture3$eel_cou_code<-factor(aquaculture3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
title <- paste("Aquaculture per country,","all stages and all habitats")

g_aquaculture <-  ggplot(aquaculture3) + 
        geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code), position='stack')+
        ggtitle(title) + xlab("year") + ylab("Aquaculture (tonnes)")+
        scale_fill_manual("Country",values=color_countries)+
        theme_bw()  
print(g_aquaculture)

```
\newline


## Release
\newline

```{r release_Gt,echo=FALSE, warning=FALSE}

##Table release (nb) for all the countries for G
release2<-release[release$eel_typ_id==9 & release$eel_lfs_code=="G",]
year<-unique(release2$eel_year)
country<-unique(release2$eel_cou_code)
hty<-unique(release2$eel_hty_code)
filtered_data<-filter_data("release2",
              typ = 9,
             life_stage = "G", 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)

##Table
fun.agg<-function(X){if(length(X)>0){round(sum(X)/10^6,ifelse(sum(X)>10^6,0,3))}else{sum(c(X,NA))}}
table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
              table<-data.frame(table,sum=rowSums(table[,-1],na.rm=T))

              
              #ordering the column accordign to country order
              country_to_order = names(table)[-1]
              n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
              n_order <- n_order+1
              n_order <- c(1,n_order)
             table = table[, n_order]
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tableRelG<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 6: Release (nb in millions) of glass eels","(",min(year),"-",max(year),")","for",paste(paste(country,collapse=","), ".", sep="")))

```

\newline

```{r release_Gf,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 6: Released (in thousands) per country, stage = G and habitat = F+T+C.", fig.height=5, fig.width=10}

##Graph
release3<-grouped_data
release3$eel_value <- as.numeric(release3$eel_value) / 1000
release3$eel_cou_code = as.factor(release3$eel_cou_code)
release3$eel_cou_code<-factor(release3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
title <- paste("Released per country,", "stage = G", "and habitat =", paste(hty,collapse="+"))

    g_release_G <-  ggplot(release3) + 
        geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code), position='stack')+
        ggtitle(title) + xlab("year") + ylab("1000 * Release (n)")+
        scale_fill_manual("Country",values=color_countries)+
        theme_bw() 
    
    print(g_release_G)

```

\newline

```{r release_Yt,echo=FALSE, warning=FALSE}

##Table release (nb) for all the countries for Y
release2<-release[release$eel_typ_id==9 & release$eel_lfs_code=="Y",]
year<-unique(release2$eel_year)
country<-unique(release2$eel_cou_code)
hty<-unique(release2$eel_hty_code)
filtered_data<-filter_data("release2",
              typ = 9,
             life_stage = "Y", 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)
fun.agg<-function(X){if(length(X)>0){round(sum(X)/10^6,ifelse(sum(X)>10^6,0,3))}else{sum(c(X,NA))}}
table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
              table<-data.frame(table,sum=rowSums(table[,-1],na.rm=T))

              
              #ordering the column accordign to country order
              country_to_order = names(table)[-1]
              n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
              n_order <- n_order+1
              n_order <- c(1,n_order)
             table = table[, n_order]
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tableRelY<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 7: Release (nb in millions) of yellow eels  ","(",min(year),"-",max(year),")"," for ",paste(paste(country,collapse=","), ".", sep="")))

```

\newline

```{r release_Yf,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 7:Released (in thousands) per country,stage = Y and habitat = F+C+T.", fig.height=5, fig.width=10}
##Graph

release3<-grouped_data
release3$eel_value <- as.numeric(release3$eel_value) / 1000
release3$eel_cou_code = as.factor(release3$eel_cou_code)
release3$eel_cou_code<-factor(release3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
title <- paste("Released per country,", "stage = Y", "and habitat =", paste(hty,collapse="+"))

    g_release_Y <-  ggplot(release3) + 
        geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code), position='stack')+
        ggtitle(title) + xlab("year") + ylab("1000 * Release (n)")+
        scale_fill_manual("Country",values=color_countries)+
        theme_bw() 
    
    print(g_release_Y)

```

\newline

```{r release_St,echo=FALSE, warning=FALSE}

##Table release (nb) for all the countries and S
release2<-release[release$eel_typ_id==9 & release$eel_lfs_code=="S",]
year<-unique(release2$eel_year)
country<-unique(release2$eel_cou_code)
hty<-unique(release2$eel_hty_code)
filtered_data<-filter_data("release2",
              typ = 9,
             life_stage = "S", 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)
fun.agg<-function(X){if(length(X)>0){round(sum(X)/10^6,ifelse(sum(X)>10^6,0,3))}else{sum(c(X,NA))}}
table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
              table<-data.frame(table,sum=rowSums(table[,-1],na.rm=T))

              
              #ordering the column accordign to country order
              country_to_order = names(table)[-1]
              n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
              n_order <- n_order+1
              n_order <- c(1,n_order)
             table = table[, n_order]
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tableRelS<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 8: Release (nb in millions) of silver eels  ","(",min(year),"-",max(year),")"," for ",paste(paste(country,collapse=","), ".", sep="")))

```

\newline

```{r release_Sf,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 8: Released (in thousands) per country, stage = S and habitat = F+T+MO+C.", fig.height=5, fig.width=10}

##Graph
release3<-grouped_data
release3$eel_value <- as.numeric(release3$eel_value) / 1000
release3$eel_cou_code = as.factor(release3$eel_cou_code)
release3$eel_cou_code<-factor(release3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
title <- paste("Released per country,", "stage = S", "and habitat =", paste(hty,collapse="+"))

    g_release_S <-  ggplot(release3) + 
        geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code), position='stack')+
        ggtitle(title) + xlab("year") + ylab("1000 * Release (n)")+
        scale_fill_manual("Country",values=color_countries)+
        theme_bw() 
    
    print(g_release_S)
```

\newline

```{r release_QGt,echo=FALSE, warning=FALSE}

##Table release (nb) for all the countries for QG

release2<-release[release$eel_typ_id==9 & release$eel_lfs_code=="QG",]
year<-unique(release2$eel_year)
country<-unique(release2$eel_cou_code)
hty<-unique(release2$eel_hty_code)
filtered_data<-filter_data("release2",
              typ = 9,
             life_stage = "QG", 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)
fun.agg<-function(X){if(length(X)>0){round(sum(X)/10^6,ifelse(sum(X)>10^6,0,3))}else{sum(c(X,NA))}}
table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
              table<-data.frame(table,sum=rowSums(table[,-1],na.rm=T))

              
              #ordering the column accordign to country order
              country_to_order = names(table)[-1]
              n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
              n_order <- n_order+1
              n_order <- c(1,n_order)
             table = table[, n_order]
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tableRelQG<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 9: Release (nb in millions) of quarantine glass eels  ","(",min(year),"-",max(year),")"," for ",paste(paste(country,collapse=","), ".", sep="")))

```

\newline

```{r release_QGf,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 9: Released (in thousands) per country, stage = QG and habitat = C+F.", fig.height=5, fig.width=10}

##Graph
release3<-grouped_data
release3$eel_value <- as.numeric(release3$eel_value) / 1000
release3$eel_cou_code = as.factor(release3$eel_cou_code)
release3$eel_cou_code<-factor(release3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
title <- paste("Released per country,", "stage = QG", "and habitat =", paste(hty,collapse="+"))

    g_release_QG <-  ggplot(release3) + 
        geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code), position='stack')+
        ggtitle(title) + xlab("year") + ylab("1000 * Release (n)")+
        scale_fill_manual("Country",values=color_countries)+
        theme_bw() 
    
    print(g_release_QG)

```

\newline

```{r release_OGt,echo=FALSE, warning=FALSE}

##Table release (nb) for all the countries
release2<-release[release$eel_typ_id==9 & release$eel_lfs_code=="OG",]
year<-unique(release2$eel_year)
country<-unique(release2$eel_cou_code)
hty<-unique(release2$eel_hty_code)
filtered_data<-filter_data("release2",
              typ = 9,
             life_stage = "OG", 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)
fun.agg<-function(X){if(length(X)>0){round(sum(X)/10^6,ifelse(sum(X)>10^6,0,3))}else{sum(c(X,NA))}}
table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
              table<-data.frame(table,sum=rowSums(table[,-1],na.rm=T))

              
              #ordering the column accordign to country order
              country_to_order = names(table)[-1]
              n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
              n_order <- n_order+1
              n_order <- c(1,n_order)
             table = table[, n_order]
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tableRelOG<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 10: Release (nb in millions) of ongrown eels  ","(",min(year),"-",max(year),")"," for ",paste(paste(country,collapse=","), ".", sep="")))

```

\newline

```{r release_OGf,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 10: Released (in thousands) per country, stage = OG and habitat = C+F+T.", fig.height=5, fig.width=10}

##Graph
release3<-grouped_data
release3$eel_value <- as.numeric(release3$eel_value) / 1000
release3$eel_cou_code = as.factor(release3$eel_cou_code)
release3$eel_cou_code<-factor(release3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
title <- paste("Released per country,", "stage = OG", "and habitat =", paste(hty,collapse="+"))

    g_release_OG <-  ggplot(release3) + 
        geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code), position='stack')+
        ggtitle(title) + xlab("year") + ylab("1000 * Release (n)")+
        scale_fill_manual("Country",values=color_countries)+
        theme_bw() 
    
    print(g_release_OG)

```

\newline

```{r release_all_stages,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 11: Released (in thousands) per country, habitat = C+F+T+MO and stage = Y+YS+OG+S+QG+AL.", fig.height=5, fig.width=10}

##Table release (nb) for all the countries
release2<-release[release$eel_typ_id==9,]
year<-unique(release2$eel_year)
country<-unique(release2$eel_cou_code)
hty<-unique(release2$eel_hty_code)
filtered_data<-filter_data("release2",
              typ = 9,
             life_stage = lfs, 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)

##Graph
release3<-grouped_data
release3$eel_value <- as.numeric(release3$eel_value) / 1000
release3$eel_cou_code = as.factor(release3$eel_cou_code)
release3$eel_cou_code<-factor(release3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
title <- paste("Released per country,", "habitat =", paste(hty,collapse="+"), "and", "stage =", paste(lfs,collapse="+"))

    g_release_all <-  ggplot(release3) + 
        geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code), position='stack')+
        ggtitle(title) + xlab("year") + ylab("1000 * Release (n)")+
        scale_fill_manual("Country",values=color_countries)+
        theme_bw() 
    
    print(g_release_all)

```
\newline

### Raw + corr commercial Landings
\newline

```{r corr_com_Gt,echo=FALSE, warning=FALSE}

##Table raw + corr commercial landings for Glass eel and every country
landings2<-landings[landings$eel_lfs_code=="G" & landings$eel_typ_id==4,]
year<-unique(landings2$eel_year)
country<-unique(landings2$eel_cou_code)
country<-country[country!="IE"]
hty<-unique(landings2$eel_hty_code)
filtered_data<-filter_data("landings2",
              typ = 4,
             life_stage = "G", 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)
fun.agg<-function(X){if(length(X)>0){round(sum(X)/1000,ifelse(sum(X)>1000,0,3))}else{sum(c(X,NA))}}
grouped_data$eel_cou_code = as.factor(grouped_data$eel_cou_code)                       
grouped_data <- predict_missing_values(grouped_data, verbose=FALSE, na.rm=FALSE) 

##Table
table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
                table2=dcast(grouped_data, eel_year~eel_cou_code, value.var = "predicted",fun = prod)
                

                #ordering the column accordign to country order
                country_to_order = names(table)[-1]
                n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
                n_order <- n_order+1
                n_order <- c(1,n_order)
                table = table[, n_order]
                
                #add a column with the sum of all the values and prod of predicted
                
                table<-data.frame(table,sum=rowSums(table[,-1],na.rm = TRUE))
                table2<-data.frame(table2,prod=apply(table2[,-1],1,prod,na.rm = TRUE))
                
                #add a * when the data is predicted
                
                for (col in 2:ncol(table)){
                  table[,col][table2[,col]==0]<-paste0(table[,col][table2[,col]==0],"*")
                }
                
                 
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tableCorrLandG<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 11: Raw+ corr commercial landings (tonnes) for glass eels  ","(",min(year),"-",max(year),")"," for ",paste(paste(country,collapse=","), ".", sep="")))

```

\newline

```{r corr_com_Gf,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 12: Raw + Corrected Commercial landings per country, stage = G and habitat = T+F+C+MO.", fig.height=5, fig.width=10}

##Graph
landings3<-grouped_data
landings3$eel_cou_code<-factor(landings3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
landings_year<-aggregate(eel_value~eel_year, landings3, sum)
title <- paste("Raw + Corrected Commercial landings per country,", "stage = G", "and habitat =", paste(hty,collapse="+"))

  g_reconstructed_landings <- ggplot(landings3) + 
      geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code),position='stack')+
      ggtitle(title)+ 
      xlab("Year") + ylab("Landings (tonnes)")+
      coord_cartesian(expand = FALSE, ylim = c(0, max(landings_year$eel_value)*1.6)) +
      scale_fill_manual("Country",values=color_countries)+
      theme_bw()
  
  # percentage of original data
  g_percentage_reconstructed <- ggplot(landings3)+
      geom_col(aes(x=eel_year,y=eel_value,fill=!predicted),position='stack')+
      xlab("") + 
      ylab("")+
      scale_fill_manual(name = "Data", values=c("black","grey"),labels=c("Predicted","Raw"))+
      theme_bw()+    
      theme(legend.position="top")
  
  
  g3_grob <- ggplotGrob(g_percentage_reconstructed)
  g_combined_landings_G <- g_reconstructed_landings+
      annotation_custom(g3_grob, 
          xmin=min(landings3$eel_year), 
          xmax=max(landings3$eel_year), 
          ymin=max(landings_year$eel_value)*1.05, 
          ymax=max(landings_year$eel_value)*1.6)
  print(g_combined_landings_G)


```

\newline

```{r corr_com_YSt,echo=FALSE, warning=FALSE}

##Table raw + corr commercial landings for Glass eel and every country
landings2<-landings[landings$eel_lfs_code %in% c("Y","S") & landings$eel_typ_id==4,]
year<-unique(landings2$eel_year)
country<-unique(landings2$eel_cou_code)
country<-country[country!="IE"]
hty<-unique(landings2$eel_hty_code)
filtered_data<-filter_data("landings2",
              typ = 4,
             life_stage = c("Y","S","YS"), 
              country = country,
            habitat = hty,
             year_range = min(year):max(year))
grouped_data <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE,na.rm=FALSE)
fun.agg<-function(X){if(length(X)>0){round(sum(X)/1000,ifelse(sum(X)>1000,0,3))}else{sum(c(X,NA))}}
grouped_data$eel_cou_code = as.factor(grouped_data$eel_cou_code)                       
grouped_data <- predict_missing_values(grouped_data, verbose=FALSE, na.rm=FALSE) 

table = dcast(grouped_data, eel_year~eel_cou_code, value.var = "eel_value",fun.aggregate = fun.agg)
                table2=dcast(grouped_data, eel_year~eel_cou_code, value.var = "predicted",fun = prod)
                

                #ordering the column accordign to country order
                country_to_order = names(table)[-1]
                n_order = order(country_ref$cou_order[match(country_to_order, country_ref$cou_code)])
                n_order <- n_order+1
                n_order <- c(1,n_order)
                table = table[, n_order]
                
                #add a column with the sum of all the values and prod of predicted
                
                table<-data.frame(table,sum=rowSums(table[,-1],na.rm = TRUE))
                table2<-data.frame(table2,prod=apply(table2[,-1],1,prod,na.rm = TRUE))
                
                #add a * when the data is predicted
                
                for (col in 2:ncol(table)){
                  table[,col][table2[,col]==0]<-paste0(table[,col][table2[,col]==0],"*")
                }
                
                 
# options(knitr.kable.NA="") this does not work
names(table)[1]<-"Year"
table[is.na(table)]<-''
tableCorLandYS<-table
kable(format(table,digt=3,drop0trailing=TRUE),format="pandoc",caption =paste("Table 12: Raw+ corr commercial landings (tonnes) for yellow and silver eels  ","(",min(year),"-",max(year),")"," for ",paste(paste(country,collapse=","), ".", sep="")))
```

\newline

```{r corr_com_YSf,echo=FALSE, warning=FALSE, fig.cap="\\label{fig:figs}Figure 13: Raw + Corrected Commercial landings per country, stage = Y+S and habitat = F+C+T+MO.", fig.height=5, fig.width=10}
##Graph
#landings_year <- dataset
landings3<-grouped_data
landings3$eel_cou_code<-factor(landings3$eel_cou_code,levels=country_ref$cou_code,ordered=TRUE)
landings_year<-aggregate(eel_value~eel_year, landings3, sum)
title <- paste("Raw + Corrected Commercial landings per country,", "stage = Y+S", "and habitat =", paste(hty,collapse="+"))

  g_reconstructed_landings <- ggplot(landings3) + 
      geom_col(aes(x=eel_year,y=eel_value,fill=eel_cou_code),position='stack')+
      ggtitle(title)+ 
      xlab("Year") + ylab("Landings (tonnes)")+
      coord_cartesian(expand = FALSE, ylim = c(0, max(landings_year$eel_value)*1.6)) +
      scale_fill_manual("Country",values=color_countries)+
      theme_bw()
  
  # percentage of original data
  g_percentage_reconstructed <- ggplot(landings3)+
      geom_col(aes(x=eel_year,y=eel_value,fill=!predicted),position='stack')+
      xlab("") + 
      ylab("")+
      scale_fill_manual(name = "Data", values=c("black","grey"),labels=c("Predicted","Raw"))+
      theme_bw()+    
      theme(legend.position="top")
  
  
  g3_grob <- ggplotGrob(g_percentage_reconstructed)
  g_combined_landings_YS <- g_reconstructed_landings+
      annotation_custom(g3_grob, 
          xmin=min(landings3$eel_year), 
          xmax=max(landings3$eel_year), 
          ymin=max(landings_year$eel_value)*1.05, 
          ymax=max(landings_year$eel_value)*1.6)
  print(g_combined_landings_YS)


```


```{r save_graphs_and_tables,echo=FALSE, warning=FALSE}

#data_directory <- wg_choose.dir(caption = "Where do you want to save the tables and the graphs")
#setwd(data_directory)

write.csv2(tableComLandG,"Raw_Com_landings_G.csv",row.names=FALSE)
write.csv2(tableComLandYS,"Raw_Com_landings_Y_S.csv",row.names=FALSE)
write.csv2(tableRecLandYS,"Raw_Rec_landings_Y_S.csv",row.names=FALSE)
write.csv2(tablerecLandG,"Raw_Rec_landings_G.csv",row.names=FALSE)
write.csv2(tableAqua,"Aquaculture_tons.csv",row.names=FALSE)
write.csv2(tableRelG,"releases_nb_G.csv",row.names=FALSE)
write.csv2(tableRelS,"releases_nb_S.csv",row.names=FALSE)
write.csv2(tableRelY,"releases_nb_Y.csv",row.names=FALSE)
write.csv2(tableRelQG,"releases_nb_QG.csv",row.names=FALSE)
write.csv2(tableRelOG,"releases_nb_OG.csv",row.names=FALSE)
write.csv2(tableCorrLandG,"Raw_Corr_Com_landings_G.csv",row.names=FALSE)
write.csv2(tableCorLandYS,"Raw_Corr_Com_landings_Y_S.csv",row.names=FALSE)

ggsave("Raw_Com_landings_G.png", g_raw_Clandings_G, device = "png", width = 30, height = 20, 
            units = "cm")
ggsave("Raw_Com_landings_YS.png", g_raw_Clandings_YS, device = "png", width = 30, height = 20, 
            units = "cm")
ggsave("Raw_Rec_landings_G.png", g_raw_Rlandings_G, device = "png", width = 30, height = 20,  
            units = "cm")
ggsave("Raw_Rec_landings_YS.png", g_raw_Rlandings_YS, device = "png", width = 30, height = 20,  
            units = "cm")
ggsave("Aquaculture.png", g_aquaculture, device = "png", width = 30, height = 20,
            units = "cm")

ggsave("Releases_G.png", g_release_G, device = "png", width = 30, height = 20,  
            units = "cm")
ggsave("Releases_Y.png", g_release_Y, device = "png", width = 30, height = 20,  
            units = "cm")
ggsave("Releases_S.png", g_release_S, device = "png", width = 30, height = 20,  
            units = "cm")
ggsave("Releases_QG.png", g_release_QG, device = "png", width = 30, height = 20, 
            units = "cm")
ggsave("Releases_OG.png", g_release_OG, device = "png", width = 30, height = 20, 
            units = "cm")
ggsave("Raw_Corr_com_landings_YS.png", g_combined_landings_YS, device = "png", width = 30, height = 20, 
            units = "cm")
ggsave("Raw_Corr_com_landings_G.png", g_combined_landings_G, device = "png", width = 30, height = 20, 
            units = "cm")

```
