---
title: "Country report export for `r if (exists('params')) params$country else 'test'`"
author: "ICES EIFAAC GFCM wgeel - Data Group"
date: "`r Sys.Date()`"
documentclass: article
output: 
  bookdown::html_document2:
    keep_md: true
    self_contained: true
    fig_caption: true
    number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: true
params:
  year:
    label: "year start"
    value: 1960
    input: slider
    min: 1900
    max: 2023
    step: 1
    sep: ""
  country:   
    label: "Country"
    value: ES
    input: select
    choices: ["BE","DE","DK","EE","ES","FI","FR","GB","GR","HR","IE","IT","LT","LV","NL","NO","PL","PT","SE","SI","TN","TR"]
  area:
    label: Area
    value: "Elsewhere Europe"
    input: radio
    choices: ["Elsewhere Europe","North Sea"]
  G:   
    label: "Glass eel"
    value: TRUE
  Y:   
    label: "Yellow eel"
    value: TRUE
  YS:   
    label: "Yellow silver eel"
    value: TRUE    
  S:   
    label: "Silver eel"
    value: TRUE
  Gr:   
    label: "Glass eel rec"
    value: TRUE
  Yr:   
    label: "Yellow eel rec"
    value: TRUE
  YSr:   
    label: "Yellow silver eel rec"
    value: TRUE    
  Sr:   
    label: "Silver eel rec"
    value: TRUE
  releaseG:   
    label: "Release G"
    value: TRUE
  releaseOG:   
    label: "Release OG"
    value: TRUE
  releaseQG:   
    label: "Release QG"
    value: TRUE
  releaseY:   
    label: "Release Y"
    value: TRUE
  releaseYS:   
    label: "Release YS"
    value: TRUE    
  releaseS:   
    label: "Release S"
    value: TRUE
  map:
    
    label: "Draw maps"
    value: TRUE
---

```{r setup, include=FALSE}
#CY=2023
CY=lubridate::year(Sys.time())


output_format = knitr::opts_knit$get("rmarkdown.pandoc.to")
if (is.null(output_format)){
  table_function <- "kable"
} else {
  table_function <- switch(output_format,
                           "docx" = "flextable",
                           "html" = "kable")
}
nrow_formatted <- function(x){
  if (table_function == "flextable"){
    flextable::nrow_part(x,part="body")
  } else{
    nrow(x)
  }
}


require(knitr)
knitr::opts_chunk$set(echo = FALSE, warnings=FALSE, fig.width=12, fig.height=8, message=FALSE,error = TRUE) # error TRUE don't stop on error
opts_knit$set(eval.after = 'fig.cap' ) # to be used in chunks used only to plot pictures
options(knitr.table.format = 'pandoc') # options pour kable
options(knitr.kable.NA = '.')
my_pandoc_to <- knitr::opts_knit$get('rmarkdown.pandoc.to') # this variable will tell the kind of compilation used
getUsername <- function(){
	name <- Sys.info()[["user"]]
	return(name)
}
if (getUsername() == "hdrouineau") setwd("~/Documents/Bordeaux/migrateurs/WGEEL/github/wg_WGEEL/R/Rmarkdown/") 
if (getUsername() == "cedric.briand") setwd("C:/workspace/wg_WGEEL/R/Rmarkdown")
if (getUsername() == "cboulenger") setwd("C:/Users/cboulenger/Documents/wg_WGEEL/R/Rmarkdown") 
if (!exists("params")){
	warnings("You are not using Rstudio or rmarkdown::render, params have been set by default setup")
	params <- list("country"='ES',G=TRUE,Y=TRUE,YS=TRUE,S=TRUE,Gr=TRUE,Yr=TRUE,YSr=TRUE,Sr=TRUE,
			releaseG=TRUE, releaseY=TRUE,releaseQG=TRUE,releaseOG=TRUE,releaseYS=TRUE,releaseS=TRUE,
			year=1960, area="Elsewhere Europe", map=TRUE)
}
```



```{r formatting table, echo=FALSE, include=FALSE}
nice_table <- function(data, digits = 2, caption = ""){
  if (table_function == "kable"){
    kable(data, digits=digits,caption=caption)
  } else if(table_function== "flextable"){
    flextable::set_flextable_defaults(digits=digits)
    flextable::flextable(data) %>%
      flextable::set_caption(caption) %>%
      flextable::autofit()
  }
}
```

```{r load_utilities, eval=TRUE, echo=FALSE,include=FALSE}

source("../utilities/load_library.R")

#-----------------
# other libraries
#-----------------
load_package("readxl")
load_package("stringr")
load_package("tidyverse")
load_package("rlang")
load_package("dplyr")
load_package("RColorBrewer")
load_package("scales")
load_package('stringr') # text handling
load_package("ggplot2") # for excel
load_package("gridExtra")
load_package("colorspace")
load_package("ggrepel")
load_package("viridis")
load_package("glue")
library(kableExtra)
load_package("pander")
load_package("ggmap")
load_package("sp")
load_package("yaml")


# load functions ------------------------------------------------------------------------------------
# retrieve reference tables needed
# the shiny is launched from shiny_data_integration/shiny thus we need the ../
if(is.null(options()$sqldf.RPostgreSQL.user)) {
	wd <- getwd()
	setwd("../shiny_data_visualisation/shiny_dv")
	source("database_connection.R")
	source("database_reference.R")
	source("database_data.R")
	source("database_precodata.R")
	source("preco_diagram.R")
	source("graphs.R")
	source("maps.R")
	source("filter_and_group_functions.R")
	source("predict_missing.R")
	setwd(wd)
}


load("../shiny_data_visualisation/shiny_dv/data/maps_for_shiny.Rdata") 
# now data are generated by the script load_data_from_the_database.R
load("../shiny_data_visualisation/shiny_dv/data/ref_and_eel_data.Rdata")
# Download the colors by country
load("../shiny_data_visualisation/shiny_dv/data/recruitment/wger.Rdata")
load("../shiny_data_visualisation/shiny_dv/data/recruitment/wger_init.Rdata") # before selection process
load("../shiny_data_visualisation/shiny_dv/data/recruitment/statseries.Rdata")
load("../shiny_data_visualisation/shiny_dv/data/recruitment/glass_eel_yoy.Rdata")
load("../shiny_data_visualisation/shiny_dv/data/recruitment/older.Rdata")
load("../shiny_data_visualisation/shiny_dv/data/recruitment/R_stations.Rdata")
load("../shiny_data_visualisation/shiny_dv/data/recruitment/dat_ge.Rdata") ; # named dat_ge
load("../shiny_data_visualisation/shiny_dv/data/recruitment/dat_ye.Rdata") ; # named dat_ye
dat_ye$area <- "Yellow"
load("../shiny_data_visualisation/shiny_dv/data/recruitment/recruitment_models.Rdata") # named model_ge_area and model_older
values=c(RColorBrewer::brewer.pal(12,"Set3"),
		RColorBrewer::brewer.pal(12, "Paired"), 
		RColorBrewer::brewer.pal(8,"Accent"),
		RColorBrewer::brewer.pal(8, "Dark2"))
color_countries = setNames(values,country_ref$cou_code)
nrtable <-  0
nrfigure <- 0

# fix pb with duplicates
wger_ys <- wger_ys %>% filter(das_qal_id<5&!is.na(das_qal_id))


```






```{r functions, echo=FALSE, warning=FALSE}
fun.agg<-function(X, scalef){
	if(length(X)>0){
		round(sum(X)/scalef,ifelse(sum(X)>scalef,0,3))
	}
	else{
		sum(c(X,NA))
	}
}
# dataset="landings"; country= 'ES';dataset="landings"; typ=6 ; life_stage="YS"; habitat=NULL; year_range=1980:2020; scalef=1000
# table_pc(dataset="landings", country= 'FR', typ=4 , life_stage="G", habitat=NULL, year_range=1980:2020)
library(ggthemes)
#' table per country, only pass one stage
table_pc <- function(country, 
		dataset, 
		typ=NULL, 
		life_stage = NULL, 
		habitat=NULL, 
		year_range = 1900:2100, 
		scalef=1){
	filtered_data <- filter_data(dataset = dataset,
			typ = typ,
			life_stage = life_stage,
			country = country,
			habitat = habitat,
			year_range = year_range
	)%>% dplyr::filter(is.na(eel_missvaluequal))
	if (nrow(filtered_data)>0){
		grouped_data <-group_data(filtered_data,
				geo = "emu",
				habitat = FALSE,
				lfs = FALSE,
				na.rm=TRUE)
		# dcast take a ... arguments and additional params can be passed to fun.aggreagate
		table <- reshape2::dcast(grouped_data, 
				eel_year~eel_emu_nameshort, 
				value.var = "eel_value",
				fun.aggregate = fun.agg,
				scalef = scalef)
		
		table <- dplyr::rename(table, year="eel_year")
		if(ncol(table))
			table<-data.frame(table,
					Sum=rowSums(table[,-1,drop=FALSE],na.rm=T)
			)
		colnames(table)[2:(ncol(table)-1)]<-substr(colnames(table)[2:(ncol(table)-1)],4,10)
		
		the_kable <- nice_table(table,			
				digits=2, caption=paste(dataset,life_stage,ifelse(typ==6,"recreational","")))
	} else {
		the_kable <- nice_table(data.frame("warning"="no data"))  
	}
	return(the_kable)
}

# dataset="landings"; country= 'IE';dataset="landings"; typ=4 ; life_stage="Y"; habitat=NULL; year_range=1980:2020; 
# geo="emu";grouphabitat=FALSE; grouplfs=FALSE;  ylab. <- "Landings T"
#' plot per country only pass one stage
plot_pc <- function(country, dataset, 
		typ=NULL, 
		life_stage = NULL,
		habitat=NULL, 
		year_range = 1900:2100,	
		ylab.="Landings T", 
		scalef=1){
	filtered_data <- filter_data(dataset = dataset,
			typ = typ,
			life_stage = life_stage,
			country = country,
			habitat = habitat,
			year_range = year_range
	)%>% dplyr::filter(is.na(eel_missvaluequal)) 
	grouped_data <- group_data(filtered_data,
			geo = "emu",
			habitat = FALSE,
			lfs = FALSE,
			na.rm=TRUE)
	grouped_data$eel_value <- as.numeric(grouped_data$eel_value)/scalef
	grouped_data$eel_emu_nameshort = as.factor(grouped_data$eel_emu_nameshort)
	emus <- levels(grouped_data$eel_emu_nameshort)
	if (length(emus) <11) palette <- gdocs_pal()(length(emus)) else palette <- sequential_hcl(length(emus), "Viridis")
	#palette	[grep("total",emus)] <- "grey50"
	if (nrow(grouped_data) > 0) {
		gg <- 	ggplot(grouped_data) + 
				geom_col(aes(x=eel_year,y=eel_value,fill=eel_emu_nameshort), position='stack')+
				xlab("year") + 
				ylab(ylab.)+		
				scale_fill_manual(values=palette)+
				theme_gdocs()
	} else {
		gg <- ggplot() +
				theme_void() +
				geom_text(aes(0,0,label='N/A')) +
				xlab(NULL)
	}
	
	return(gg)
}
# dataset="release"; country= 'FR'; typ=9 ; life_stage=c("G","Y","QG","OG","YS","S"); habitat=NULL; year_range=1980:2020; 
# geo="emu";grouphabitat=FALSE; grouplfs=FALSE;
#' Table per country per lifestage.
table_pc_lfs <- function(country, dataset, typ = 9,
		life_stage=c("G","Y","QG","OG","YS","S"),  
		year_range = 1900:2100, 
		habitat=FALSE, 
		scalef=1){
	filtered_data <- filter_data(dataset = dataset,
			typ = typ,
			life_stage = life_stage,
			country = country,
			year_range = year_range
	)%>% dplyr::filter(is.na(eel_missvaluequal)) 
	if (nrow(filtered_data)>0){
		grouped_data <-group_data(filtered_data,
				geo = "emu",
				habitat = FALSE,
				lfs = TRUE,
				na.rm=TRUE)
		table = reshape2::dcast(grouped_data, 
				eel_year~eel_emu_nameshort+eel_lfs_code, 
				value.var = "eel_value",
				fun.aggregate = fun.agg,
				scalef = scalef)
		
		table <- dplyr::rename(table, year="eel_year")
		table<-data.frame(table,
				Sum=rowSums(table[,-1,drop=FALSE],na.rm=T)
		)
		colnames(table)<-gsub(paste("^",country,"_",sep=""),
				"",
				colnames(table))
		caption=ifelse(typ %in% c(8,9),
				paste("Release in", ifelse(typ==8,"kg","number")),
				"Aquaculture in tons")
		the_kable <- nice_table(table,			
				digits=2,
				caption=caption)
	} else {
		the_kable <- nice_table(data.frame("warning"="no data"))  
	}
	return(the_kable)
}
#' Plot per country per life stage
plot_pc_lfs <- function(country, 
		dataset, 
		typ=NULL, 
		life_stage = NULL, 
		habitat=NULL, 
		year_range = 1900:2100, 
		ylab.="Landings T",  
		scalef=1){
	filtered_data <- filter_data(dataset = dataset,
			typ = typ,
			life_stage = life_stage,
			country = country,
			habitat = habitat,
			year_range = year_range
	)%>% dplyr::filter(is.na(eel_missvaluequal)) 
	grouped_data <- group_data(filtered_data,
			geo = "emu",
			habitat = FALSE,
			lfs = TRUE,
			na.rm=TRUE)
	grouped_data$eel_value <- as.numeric(grouped_data$eel_value)/scalef
	grouped_data$eel_emu_nameshort = as.factor(grouped_data$eel_emu_nameshort)
	emus <- levels(grouped_data$eel_emu_nameshort)
	if (length(emus) <11) palette <- gdocs_pal()(length(emus)) else palette <- sequential_hcl(length(emus), "Viridis")
	#palette	[grep("total",emus)] <- "grey50"
	if (nrow(grouped_data) > 0) {
		gg <- 	ggplot(grouped_data) + 
				geom_col(aes(x=eel_year,y=eel_value,fill=eel_emu_nameshort), position='stack')+
				xlab("year") + 
				ylab(ylab.)+		
				scale_fill_manual(values=palette)+
				facet_wrap(~eel_lfs_code)
		theme_gdocs()
	} else {
		gg <- ggplot() +
				theme_void() +
				geom_text(aes(0,0,label='N/A')) +
				xlab(NULL)
	}
	
	return(gg)
}


figure_recruitment <- function(){	
	
	# These values are standardized against the predictions in 1960s-1970s
	# the predictions are the predictions of the expand.grid(year,site,area)		
	# this is the North Sea or Elswhere Europe series
	
	the_series <-  	dat_ge[,c("year",
					"p", # predictions in the log scale for EE or NS series
					"mean", # mean of predictions 1960-1979 log scale
					"p_std_1960_1979", # scaled prediction exp(p-mean)
					"p_std_1960_1979_min",     
					"p_std_1960_1979_max",
					"p_std_1960_1979_maxgraph")]
	
	# extracting scaled value for the plot -------------------------------------------
	model_data <- model_ge_area$model 	
	df_coeff_site<- data.frame("site"=
					gsub("site","",names(coefficients(model_ge_area)[grep("site",names(coefficients(model_ge_area)))])),
			"co"= coefficients(model_ge_area)[grep("site",names(coefficients(model_ge_area)))]
	)
	
	
	selected <- model_data %>% 
			stacomirtools::killfactor()%>%
			left_join(df_coeff_site) %>%
			mutate(year=as.numeric(as.character(year_f))) %>% 
			mutate_at(c("co"),replace_na, replace = 0) %>% 
			full_join(                             
					dat_ge[,c("year",
									"area",
									"p", # predictions in the log scale for EE or NS series
									"mean", # mean of predictions 1960-1979 log scale
									"p_std_1960_1979", # scaled prediction exp(p-mean)
									"p_std_1960_1979_min",     
									"p_std_1960_1979_max",
									"p_std_1960_1979_maxgraph")],
					by=c("year", "area"))	%>% # join by year
			right_join(wger %>% dplyr::select(year, das_qal_id, site,lfs_code) %>%			         
							filter(lfs_code %in% c('G','GY')) ,
					by=c("year","site"))%>% # getting das_qal_id for the graph 
			inner_join(R_stations %>% select(ser_nameshort,cou_code) %>%rename(site = ser_nameshort ))%>%
			mutate(value_std_1960_1979=exp(log(value_std)-co-mean))	%>%
			arrange(site,year)  %>%
			mutate("selected" = TRUE) %>%
			select("year","area","cou_code","site","value_std_1960_1979","p_std_1960_1979","p_std_1960_1979_min","p_std_1960_1979_max","p_std_1960_1979_maxgraph","selected")
	
	
	not_selected <-	 wger_init %>% dplyr::select(value,year,site,ser_qal_id,area, lfs_code) %>%			         
			filter((ser_qal_id==0|ser_qal_id==3) & lfs_code %in% c('G','GY')) %>% select(value,year,site,area)
	not_selected <-	left_join(not_selected,
					not_selected %>% group_by(site) %>% summarize(meanser=mean(value,na.rm=TRUE))
			) %>% mutate(value=value/meanser) %>%
			full_join(                             
					dat_ge[,c("year",
									"area",
									"p", # predictions in the log scale for EE or NS series
									"mean", # mean of predictions 1960-1979 log scale
									"p_std_1960_1979", # scaled prediction exp(p-mean)
									"p_std_1960_1979_min",     
									"p_std_1960_1979_max",
									"p_std_1960_1979_maxgraph"
							)],
					by=c("year","area") ) %>%		
			# calculate log average when value is not missing to rescale only on the common period
			inner_join(R_stations %>% select(ser_nameshort,cou_code) %>%rename(site = ser_nameshort ))
	
	not_selected <- inner_join(not_selected,
					not_selected %>% group_by(site) %>%
							summarize(		
									mean_pred_when_existing = mean(p[!is.na(value)]), # geometric mean log scale
									mean_pred_value_std = mean(log(value),na.rm=TRUE) # mean of log of existing observed											
							)
			) %>%						
			# Standardize the value to existing predictions
			mutate(
					standardized_same_period= log(value) - mean_pred_value_std + mean_pred_when_existing
			)%>% 	 
			# calculate the value standardized to 1960_1979, the wgeel series has also been scaled by mean 
			# which is the average 1960_1979
			mutate(
					value_std_1960_1979= exp(standardized_same_period -mean), 
					selected=FALSE
			)%>%
			select("year","area","cou_code","site","value_std_1960_1979","p_std_1960_1979","p_std_1960_1979_min","p_std_1960_1979_max","p_std_1960_1979_maxgraph","selected")
	
	all_data <- rbind(selected, not_selected)	
	sites_cou <- unique(filter(all_data, cou_code==params$country)$site)
	if (length(sites_cou)>0){
		if (length(sites_cou) <11) palette <- gdocs_pal()(length(sites_cou)) else 
			palette <- gdocs_pal()(10)
		palette <- colorRampPalette(palette)(length(sites_cou))
		
		
		gg <- ggplot(filter(all_data, cou_code==params$country)) +
				geom_ribbon(data=dat_ge[dat_ge$area==params$area,],
						aes(x=year, ymin=p_std_1960_1979_min, ymax=p_std_1960_1979_max),
						size=0.5,fill="dodgerblue",alpha=0.5) +
				geom_line(data=dat_ge[dat_ge$area==params$area,],
						aes(x=year, y=p_std_1960_1979), colour="darkblue", alpha=0.2) +
				geom_point(aes(x=year, y=value_std_1960_1979, color=site),size=1.5) +
				geom_line(aes(x=year, y=value_std_1960_1979, group=site, color=site),size=0.8, alpha=0.5) +
				scale_x_continuous( limits=c(1960,CY),breaks=c(1970,1980,1990,2000,2010,2020),
						minor_breaks=seq(from=min(1960,
										to=max(all_data$year),by=2))) +
				scale_colour_manual(values=palette) +
				facet_wrap(~selected)
	} else{
		gg <- ggplot() +
				theme_void() +
				geom_text(aes(0,0,label='N/A')) +
				xlab(NULL)
	}
	return(gg)
	
}

#




figure_yellow_recruitment <- function(){	
	
	# These values are standardized against the predictions in 1960s-1970s
	# the predictions are the predictions of the expand.grid(year,site,area)		
	# this is the North Sea or Elswhere Europe series
	
	the_series <- dat_ye	%>%
			dplyr::rename(p_std_1960_1979 = value_std_1960_1979,
					p_std_1960_1979_min =yellow_eel_min,
					p_std_1960_1979_max = yellow_eel_max)
	
	# extracting scaled value for the plot -------------------------------------------
	model_data <- model_older$model 
	model_data$r <- resid(model_older)
	df_coeff_site<- data.frame("site"=
					gsub("site","",names(coefficients(model_older)[grep("site",names(coefficients(model_older)))])),
			"co"= coefficients(model_older)[grep("site",names(coefficients(model_older)))]
	)
	
	
	selected <- model_data %>% 
			stacomirtools::killfactor()%>%
			dplyr::rename("site" = "as.factor(site)", "year"="year_f") %>%
			mutate(year=as.numeric(as.character(year))) %>% 		
			left_join(df_coeff_site) %>%
			mutate_at(c("co"),replace_na, replace = 0) %>% 
			full_join(                             
					dat_ye %>% 
							dplyr::select(year,p,value_std_1960_1979,mean_1960_1979, yellow_eel_min, yellow_eel_max) %>%
							dplyr::rename(p_std_1960_1979 = value_std_1960_1979,
									mean=mean_1960_1979,
									p_std_1960_1979_min =yellow_eel_min,
									p_std_1960_1979_max = yellow_eel_max),																	
					by="year") %>% 
			right_join(wger %>% dplyr::select(year, das_qal_id, site,lfs_code) %>%			         
							filter(lfs_code %in% c('Y')) ,
					by=c("year","site"))%>% # getting das_qal_id for the graph 
			inner_join(R_stations %>% dplyr::select(ser_nameshort,cou_code) %>%dplyr::rename(site = ser_nameshort ))%>%
			mutate(value_std_1960_1979= exp(log(value_std)-co-mean))	%>%
			arrange(site,year)  %>%
			mutate("selected" = TRUE) %>%
			dplyr::select("year","cou_code","site","value_std_1960_1979","p_std_1960_1979","p_std_1960_1979_min","p_std_1960_1979_max","selected")
	
	
	not_selected <-	 wger_init %>% dplyr::select(value,year,site,ser_qal_id, lfs_code) %>%			         
			filter((ser_qal_id==0|ser_qal_id==3) & lfs_code %in% c('Y')) %>% dplyr::select(value,year,site)
	not_selected <-	
			left_join(not_selected,
					not_selected %>% 
							group_by(site) %>% 
							summarize(meanser=mean(value,na.rm=TRUE))
			) %>% mutate(value=value/meanser) %>%
			full_join(                             
					dat_ye %>% 
							dplyr::select(year,p,value_std_1960_1979,mean_1960_1979, yellow_eel_min, yellow_eel_max) %>%
							dplyr::rename(p_std_1960_1979 = value_std_1960_1979,
									mean=mean_1960_1979,
									p_std_1960_1979_min =yellow_eel_min,
									p_std_1960_1979_max = yellow_eel_max),																	
					by="year") %>%		
			# calculate log average when value is not missing to rescale only on the common period
			inner_join(R_stations %>% dplyr::select(ser_nameshort,cou_code) %>% dplyr::rename(site = ser_nameshort ))
	
	not_selected <- inner_join(not_selected,
					not_selected %>% group_by(site) %>%
							summarize(		
									mean_pred_when_existing = mean(p[!is.na(value)]), # geometric mean log scale
									mean_pred_value_std = mean(log(value),na.rm=TRUE) # mean of log of existing observed											
							)
			) %>%						
			# Standardize the value to existing predictions
			mutate(
					standardized_same_period= log(value) - mean_pred_value_std + mean_pred_when_existing
			)%>% 	 
			# calculate the value standardized to 1960_1979, the wgeel series has also been scaled by mean 
			# which is the average 1960_1979
			mutate(
					value_std_1960_1979= exp(standardized_same_period-mean), 
					selected=FALSE
			)%>%
			dplyr::select("year","cou_code","site","value_std_1960_1979","p_std_1960_1979","p_std_1960_1979_min","p_std_1960_1979_max","selected")
	
	all_data <- rbind(selected, not_selected)	
	sites_cou <- unique(filter(all_data, cou_code==params$country)$site)
	if (length(sites_cou)>0){
		if (length(sites_cou) <11) palette <- gdocs_pal()(length(sites_cou)) else 
			palette <- gdocs_pal()(10)
		palette <- colorRampPalette(palette)(length(sites_cou))
		
		
		gy <- ggplot(filter(all_data, cou_code==params$country)) +
				geom_ribbon(data=dat_ye,
						aes(x=year, ymin=yellow_eel_min, ymax=yellow_eel_max),
						size=0.5,fill="darkolivegreen2",alpha=0.5) +
				geom_line(data=dat_ye,
						aes(x=year, y=value_std_1960_1979), colour="darkgreen", alpha=0.2) +
				geom_point(aes(x=year, y=value_std_1960_1979, color=site),size=1.5) +
				geom_line(aes(x=year, y=value_std_1960_1979, group=site, color=site),size=0.8, alpha=0.5) +
				scale_x_continuous( limits=c(1960,CY),breaks=c(1970,1980,1990,2000,2010,2020),
						minor_breaks=seq(from=min(1960,
										to=max(all_data$year),by=2))) +
				scale_colour_manual(values=palette) +
				facet_wrap(~selected)
	} else{
		gy <- ggplot() +
				theme_void() +
				geom_text(aes(0,0,label='N/A')) +
				xlab(NULL)
	}
	return(gy)
	
}


figure_ys <- function(stage_selected="Y"){	
	
	
	
	idcol <- c("das_comment",
	           "das_effort",
	           "ser_effort_uni_code",
	           "das_last_update" ,
	           "das_id",
	           "ser_id",
	           "ser_area_division",
	           "f_subarea",
	           "lfs_code",
	           "lfs_name",
	           "das_qal_id")	
	
	wger_ys1 <- wger_ys %>% 
			filter(lfs_code==stage_selected) %>%	
			dplyr::select(-idcol) %>%
			pivot_wider(names_from=ser_nameshort,values_from=das_value) %>% 
			arrange(das_year)   
	
	wger_ys1
	wger_ys2 <- wger_ys1 %>% mutate_at(vars(-das_year),scale)
	
	
	wger_ys3 <- wger_ys2 %>%  pivot_longer(-das_year, names_to="ser_nameshort", values_to="scaled_value") %>%
			inner_join(ys_stations %>% dplyr::select(ser_nameshort,cou_code)) %>%
			dplyr::rename(site="ser_nameshort", year="das_year") %>%
			arrange(site,year) 
	
	
	sites_cou <- unique(filter(wger_ys3, cou_code==params$country)$site)
	if (length(sites_cou)>0){
		if (length(sites_cou) <11) palette <- gdocs_pal()(length(sites_cou)) else 
			palette <- ggthemes::gdocs_pal()(10)
		palette <- grDevices::colorRampPalette(palette)(length(sites_cou))
		
		minyear <- 	wger_ys3 %>% filter(cou_code==params$country) %>% 
				filter(!is.na(scaled_value)) %>%
				pull(year) %>%
				min()
		gy <- ggplot(filter(wger_ys3, cou_code==params$country), aes(x=year, y=scaled_value)) +		
				geom_point(aes( color=site),size=1.5) +
				geom_line(aes( group=site, color=site),size=0.8, alpha=0.5) + 
				scale_colour_manual(values=palette) +
				scale_x_continuous(limits = c(minyear,CY)) +
				stat_smooth(method=mgcv::gam,col="red", formula = y ~ s(x) )+
				theme_bw()
		
	} else{
		gy <- ggplot() +
				theme_void() +
				geom_text(aes(0,0,label='N/A')) +
				xlab(NULL)
	}
	return(gy)
	
}

map_yellow_recruitment <- function(){	
	
	# These values are standardized against the predictions in 1960s-1970s
	# the predictions are the predictions of the expand.grid(year,site,area)		
	# this is the North Sea or Elswhere Europe series
	
	
	selected <- wger_init %>% dplyr::select(site,ser_qal_id,ser_id, lfs_code) %>%	
			filter(ser_qal_id==1 & lfs_code %in% c('Y')) %>% select(site,ser_id) %>%
			distinct() %>%
			inner_join(R_stations %>% 
							select(ser_id,ser_nameshort,cou_code,ser_x,ser_y) %>%
							rename(site = ser_nameshort )) %>%
			mutate(selected=TRUE)%>%
			filter(cou_code==params$country)
	
	not_selected <-	 wger_init %>% dplyr::select(site,ser_qal_id,ser_id, lfs_code) %>%			         
			filter((ser_qal_id==0|ser_qal_id==3) & lfs_code %in% c('Y')) %>% select(site,ser_id) %>%
			distinct() %>%
			inner_join(R_stations %>% 
							select(ser_id,ser_nameshort,cou_code,ser_x,ser_y) %>%
							rename(site = ser_nameshort )) %>%
			mutate(selected=FALSE)%>%
			filter(cou_code==params$country)
	
	
	
	all_data <- rbind(selected, not_selected)	
	sites_cou <- unique(all_data$site)
	
	if (length(sites_cou)>0){
		if (length(sites_cou) <11) palette <- gdocs_pal()(length(sites_cou)) else 
			palette <- gdocs_pal()(10)
		palette <- colorRampPalette(palette)(length(sites_cou))
		
		country_map <- as(country_p,"Spatial")
		country_map	<- country_p[country_p$cou_code== params$country,]	
		location=c(left=sf::st_bbox(country_map)[1]-0.5,
				bottom=sf::st_bbox(country_map)[2]-0.5,
				right=sf::st_bbox(country_map)[3]+0.5,
				top=sf::st_bbox(country_map)[4]+0.5)
		lon_range <- location[c("left.xmin", "right.xmax")]
		lat_range <- location[c("bottom.ymin", "top.ymax")]
		lonlength <- diff(lon_range)
		latlength <- diff(lat_range)
		zoomlon <- ceiling(log2(360 * 2/lonlength))
		zoomlat <- ceiling(log2(180 * 2/latlength))
		zoom <- max(zoomlon, zoomlat)
		names(location)=c("left","bottom","right","top")
		mymap <-get_stamenmap(location,zoom=zoom,
				maptype = "terrain-background",
				source="stamen")
		
		g <- ggmap(mymap)+
				geom_point(data=all_data,
						aes(x=ser_x, y=ser_y,
								shape=as.factor(selected),
								col=site),
						cex=3)+
				scale_shape("Used in GLM")+
				scale_colour_manual(values=palette)+
				xlab("")+
				ylab("")
	} else {
		g <- ggplot() +
				theme_void() +
				geom_text(aes(0,0,label='N/A')) +
				xlab(NULL)
	}
	return(g)
}


map_recruitment <- function(){	
	
	# These values are standardized against the predictions in 1960s-1970s
	# the predictions are the predictions of the expand.grid(year,site,area)		
	# this is the North Sea or Elswhere Europe series
	
	
	selected <- wger_init %>% dplyr::select(site,ser_qal_id,ser_id, lfs_code) %>%	
			filter(ser_qal_id==1 & lfs_code %in% c('G','GY')) %>% select(site,ser_id) %>%
			distinct() %>%
			inner_join(R_stations %>% 
							select(ser_id,ser_nameshort,cou_code,ser_x,ser_y) %>%
							rename(site = ser_nameshort )) %>%
			mutate(selected=TRUE)%>%
			filter(cou_code==params$country)
	
	not_selected <-	 wger_init %>% dplyr::select(site,ser_qal_id,ser_id, lfs_code) %>%			         
			filter((ser_qal_id==0|ser_qal_id==3) & lfs_code %in% c('G','GY')) %>% select(site,ser_id) %>%
			distinct() %>%
			inner_join(R_stations %>% 
							select(ser_id,ser_nameshort,cou_code,ser_x,ser_y) %>%
							rename(site = ser_nameshort )) %>%
			mutate(selected=FALSE)%>%
			filter(cou_code==params$country)
	
	
	
	all_data <- rbind(selected, not_selected)	
	sites_cou <- unique(all_data$site)
	
	if (length(sites_cou)>0){
		if (length(sites_cou) <11) palette <- gdocs_pal()(length(sites_cou)) else 
			palette <- gdocs_pal()(10)
		palette <- colorRampPalette(palette)(length(sites_cou))
		
		#country_map <- as(country_p,"Spatial")
		country_map	<- sf::as_Spatial(sf::st_geometry(country_p[country_p$cou_code== params$country,]))	
		location=c(left=sf::st_bbox(country_map)[1]-0.5,
				bottom=sf::st_bbox(country_map)[2]-0.5,
				right=sf::st_bbox(country_map)[3]+0.5,
				top=sf::st_bbox(country_map)[4]+0.5)
		lon_range <- location[c("left.xmin", "right.xmax")]
		lat_range <- location[c("bottom.ymin", "top.ymax")]
		lonlength <- diff(lon_range)
		latlength <- diff(lat_range)
		zoomlon <- ceiling(log2(360 * 2/lonlength))
		zoomlat <- ceiling(log2(180 * 2/latlength))
		zoom <- max(zoomlon, zoomlat)
		names(location)=c("left","bottom","right","top")

		mymap <-get_stamenmap(location,zoom=zoom,
				maptype = "terrain-background",
				source="stamen")
		
		g <- ggmap(mymap)+
				geom_point(data=all_data,
						aes(x=ser_x, y=ser_y,
								shape=as.factor(selected),
								col=site),
						cex=3)+
				scale_shape("Used in GLM")+
				scale_colour_manual(values=palette)+
				xlab("")+
				ylab("")
	} else {
		gg <- ggplot() +
				theme_void() +
				geom_text(aes(0,0,label='N/A')) +
				xlab(NULL)
	}
	return(g)
}



map_ys <- function(){	
	
	station <- ys_stations %>% dplyr::select(ser_nameshort,cou_code, ser_x, ser_y, ser_lfs_code) %>%
			rename(site="ser_nameshort", stage = "ser_lfs_code") %>%
			arrange(site) %>%
			filter(cou_code==params$country)
	sites_cou <- station %>% pull(site) 
	if (length(sites_cou)>0){
		if (length(sites_cou) <11) palette <- gdocs_pal()(length(sites_cou)) else 
			palette <- ggthemes::gdocs_pal()(10)
		palette <- grDevices::colorRampPalette(palette)(length(sites_cou))
		country_map <- as(country_p,"Spatial")
		country_map	<- country_p[country_p$cou_code== params$country,]	
		location=c(left=sf::st_bbox(country_map)[1]-0.5,
				bottom=sf::st_bbox(country_map)[2]-0.5,
				right=sf::st_bbox(country_map)[3]+0.5,
				top=sf::st_bbox(country_map)[4]+0.5)
		lon_range <- location[c("left.xmin", "right.xmax")]
		lat_range <- location[c("bottom.ymin", "top.ymax")]
		lonlength <- diff(lon_range)
		latlength <- diff(lat_range)
		zoomlon <- ceiling(log2(360 * 2/lonlength))
		zoomlat <- ceiling(log2(180 * 2/latlength))
		zoom <- max(zoomlon, zoomlat)
		names(location)=c("left","bottom","right","top")
		
		mymap <-get_stamenmap(location,zoom=zoom,
				maptype = "terrain-background",
				source="stamen")
		
		g <- ggmap(mymap)+							
				geom_point(data=station,
						aes(x=ser_x, y=ser_y,
								shape = stage,								
								col=site),
						size=2)+
				geom_point(data=station[station$stage=="S",],
						aes(x=ser_x, y=ser_y),
						shape=21,						
						size = 2,
						color= "black")+		
				scale_shape("Stage")+
				scale_colour_manual(values=palette)+
				scale_size_manual(values=c(2,3))+				
				xlab("")+
				ylab("")
	} else {
		gg <- ggplot() +
				theme_void() +
				geom_text(aes(0,0,label='N/A')) +
				xlab(NULL)
	}
	return(g)
}

```



# Landings commercial fisheries
```{r G, echo=FALSE, warning=FALSE, results="asis", eval=params$G}
asis_output("## Glass eel\n")
cat("\n")
nrtable=nrtable+1
res <- table_pc(dataset="landings", 
		country=  params$country, 
		typ=4 , 
		life_stage="G",
		year_range=params$year:CY,
		scalef=1000 # in tons
)
if (table_function == "kable"){
  print(res %>% kable_styling())
}else{
  res
}
cat("\n")

```


```{r Gfig, echo=FALSE, warning=FALSE, results="asis",fig.cap="landings G", eval=params$G}
gg <-plot_pc(dataset="landings", 
		country= params$country, 
		typ=4 , 
		life_stage="G",
		year_range=1960:CY,
		scalef=1000
)
print(gg)
cat("\n")

```


	
```{r Y, echo=FALSE, warning=FALSE, results="asis", eval=params$Y}

asis_output("## Yellow eel\\n")
cat("\n")
res <- table_pc(dataset="landings", 
		country=  params$country, 
		typ=4 , 
		life_stage="Y",
		year_range=1960:CY, 
		scalef=1000
)
if (table_function == "kable"){
  print(res %>% kable_styling())
}else{
  res
}
cat("\n")

```	


```{r Yfig, echo=FALSE, warning=FALSE, results="asis",fig.cap="landings Y", eval=params$Y}

gg <-plot_pc(dataset="landings", 
		country= params$country, 
		typ=4 , 
		life_stage="Y",
		year_range=1960:CY, 		
		scalef=1000)
print(gg)
cat("\n")

```


```{r YS, echo=FALSE, warning=FALSE, results="asis", eval=params$YS}

asis_output("## Yellow silver\\n")
cat("\n")
res <- table_pc(dataset="landings", 
		country=  params$country, 
		typ=4 , 
		life_stage=c("YS"),
		year_range=1960:CY, 
		scalef=1000)
if (table_function == "kable"){
  print(res %>% kable_styling())
}else{
  (res)
}
cat("\n")
```


```{r YSfig, echo=FALSE, warning=FALSE, results="asis",fig.cap="landings YS", eval=params$YS}	
gg <-plot_pc(dataset="landings", 
		country= params$country, 
		typ=4 , 
		life_stage=c("YS"),
		year_range=1960:CY, 		
		scalef=1000)
print(gg)
cat("\n")
```


```{r S, echo=FALSE, warning=FALSE, results="asis", eval=params$S}

asis_output("## Silver silver\\n")
cat("\n")
res <- table_pc(dataset="landings", 
		country=  params$country, 
		typ=4 , 
		life_stage=c("S"),
		year_range=1960:CY, 			
		scalef=1000)
if (table_function == "kable"){
  print(res %>% kable_styling())
}else{
  res
}
cat("\n")
```



```{r Sfig, echo=FALSE, warning=FALSE, results="asis",fig.cap="landings S", eval=params$S}
gg <-plot_pc(dataset="landings", 
		country= params$country, 
		typ=4 , 
		life_stage=c("S"),
		year_range=1960:CY, 			
		scalef=1000)
print(gg)
cat("\n")
```

# Landings Recreational fisheries

```{r Gr, echo=FALSE, warning=FALSE, results="asis", eval=params$Gr}

asis_output("## Glass eel\\n")
cat("\n")
res <- table_pc(dataset="landings", 
		country=  params$country, 
		typ=6 , 
		life_stage="G",
		year_range=1960:CY, 
		scalef=1000
)
if (table_function == "kable"){
  print(res %>% kable_styling())
}else{
  res
}
cat("\n")
```



```{r Grfig, echo=FALSE, warning=FALSE, results="asis", eval=params$Gr,fig.cap="landings G recreational"}	
gg <-plot_pc(dataset="landings", 
		country= params$country, 
		typ=6 , 
		life_stage="G",
		year_range=1960:CY, 
		scalef=1000
)
print(gg)
cat("\n")
```


	
```{r Yr, echo=FALSE, warning=FALSE, results="asis", eval=params$Yr}

asis_output("## Yellow eel\\n")
cat("\n")
res <- table_pc(dataset="landings", 
		country=  params$country, 
		typ=6 , 
		life_stage="Y",
		year_range=1960:CY,
		scalef=1000
)
if (table_function == "kable"){
  print(res %>% kable_styling())
}else{
  res
}
cat("\n")
```


	
```{r Yrfig, echo=FALSE, warning=FALSE, results="asis", eval=params$Yr,fig.cap="landings Y recreational"}

gg <-plot_pc(dataset="landings", 
		country= params$country, 
		typ=6 , 
		life_stage="Y",
		year_range=1960:CY, 
		scalef=1000
)
print(gg)
cat("\n")
```

```{r YSr, echo=FALSE, warning=FALSE, results="asis", eval=params$YSr}
asis_output("## Yellow silver\\n")
cat("\n")
res <- table_pc(dataset="landings", 
		country=  params$country, 
		typ=6 , 
		life_stage=c("YS"),
		year_range=1960:CY, 
		scalef=1000)
if (table_function == "kable"){
  print(res %>% kable_styling())
}else{
  (res)
}
cat("\n")

```


```{r YSrfig, echo=FALSE, warning=FALSE, results="asis", eval=params$YSr,fig.cap="landings YS recreational"}

gg <-plot_pc(dataset="landings", 
		country= params$country, 
		typ=6 , 
		life_stage=c("YS"),
		year_range=1960:CY,
		scalef=1000)
print(gg)
cat("\n")
```


```{r Sr, echo=FALSE, warning=FALSE, results="asis", eval=params$Sr}
asis_output("## Silver eel\\n")
cat("\n")
res <- table_pc(dataset="landings", 
		country=  params$country, 
		typ=6 , 
		life_stage=c("S"),
		year_range=1960:CY, 
		scalef=1000)
if (table_function == "kable"){
  print(res %>% kable_styling())
}else{
  (res)
}
cat("\n")
```

```{r Srfig, echo=FALSE, warning=FALSE, results="asis", eval=params$Sr,fig.cap="landings S recreational"}
gg <-plot_pc(dataset="landings", 
		country= params$country, 
		typ=6 , 
		life_stage=c("S"),
		year_range=1960:CY, 
		scalef=1000)
print(gg)
cat("\n")
```


```{r releaseprep,echo=FALSE,warning=FALSE}
res_number <- table_pc_lfs(dataset="release", 
		country=  params$country, 
		typ=9 , 
		life_stage=c("G","Y","QG","OG","YS","S")[
				c(params$releaseG, params$releaseY, params$releaseQG,
						params$releaseOG, params$releaseYS, params$releaseS)],
		
		year_range=1960:CY, 
		scalef=10^6
)
release_n <- nrow_formatted(res_number)>0

res_kg <- table_pc_lfs(dataset="release", 
		country=  params$country, 
		typ=8 , 
		life_stage=c("G","Y","QG","OG","YS","S")[
				c(params$releaseG, params$releaseY, params$releaseQG,
						params$releaseOG, params$releaseYS, params$releaseS)],
		
		year_range=params$year:CY, 
		scalef=1
)

release_kg <- nrow_formatted(res_kg)>0
release_T <- release_kg | release_n
cat("\n")

```


```{r releaseheader,echo=FALSE,warning=FALSE,result="asis",eval=release_T}
asis_output("# Release\\n")
cat("\n")
```


```{r releasen, echo=FALSE, warning=FALSE, results="asis",eval=release_n}
asis_output("## In number\\n")
cat("\n")
if (table_function == "kable"){
  print(res_number %>% kable_styling())
}else{
  (res_number)
}
cat("\n")
```


```{r releasenfig, echo=FALSE, warning=FALSE, results="asis",eval=release_n,fig.cap="Release in million"}
cat("\n")
gg <- plot_pc_lfs(dataset="release", 
		country= params$country, 
		typ=9 , 
		life_stage=c("G","Y","QG","OG","YS","S")[
				c(params$releaseG, params$releaseY, params$releaseQG,
						params$releaseOG, params$releaseYS, params$releaseS)],
		year_range=params$year:CY, 
		scalef=10^6,
		ylab.="Release in million"
)
print(gg)

asis_output("<br/>")

```



```{r releasekg, echo=FALSE, warning=FALSE, results="asis",eval=release_kg}
asis_output("## In kg\\n")
cat("\n")
if (table_function == "kable"){
  print(res_kg %>% kable_styling())
}else{
  (res_kg)
}
cat("\n")
asis_output("<br/>")
cat("\n")
```



```{r releasekgfig, echo=FALSE, warning=FALSE, results="asis",eval=release_kg, fig.cap="Release in kg"}
gg <- plot_pc_lfs(dataset="release", 
		country= params$country, 
		typ=8 , 
		life_stage=c("G","Y","QG","OG","YS","S")[
				c(params$releaseG, params$releaseY, params$releaseQG,
						params$releaseOG, params$releaseYS, params$releaseS)],
		year_range=params$year:CY, 
		scalef=,
		ylab.="Release in kg"
)
print(gg)
cat("\n")
asis_output("<br/>")
```



```{r aquacultureprep,echo=FALSE,warning=FALSE}
res <- table_pc_lfs(dataset="aquaculture", 
		country=  params$country, 
		typ=11 , 
		life_stage=c("G","Y","YS","S","QG","OG"),		
		year_range=1960:CY, 
		scalef=1000	    
)
aqua_n <- nrow_formatted(res)>0
cat("\n")
```



```{r aquaculture, echo=FALSE, warning=FALSE, results="asis",eval=aqua_n}

asis_output("# Aquaculture\\n")
cat("\n")
asis_output("<br/>")
if (table_function == "kable"){
  print(res %>% kable_styling())
}else{
  (res)
}
asis_output("<br/>")
cat("\n")

```


```{r aquaculturefig, echo=FALSE, warning=FALSE, results="asis",eval=aqua_n,fig.cap="Aquaculture"}
gg <- plot_pc_lfs(dataset="aquaculture", 
		country= params$country, 
		typ=11 , 
		life_stage=c("G","Y","YS","S","QG","OG")	,
		year_range=params$year:CY, 
		scalef=1000,
		ylab.="Aquaculture in tons"
)
print(gg)
cat("\n")

```
		
```{r recruit, echo=FALSE, warning=FALSE, results="asis",fig.cap="Recruitment G+GY, panel indicate if selected"}
asis_output("# Recruitment series G+GY")
cat("\n")
g <- figure_recruitment()
glog<- g + scale_y_log10(limits=c(0.001,30),breaks=c(0.01,0.1,1,10,100,1000),
		labels=c("0.01","0.1","1","10","100","1000"))
gridExtra::grid.arrange(g+ggtitle("Natural Scale"),glog+ggtitle("Log Scale"),nrow=2)

cat("\n")
asis_output("<br/>")
```


```{r yellowr, echo=FALSE, warning=FALSE, results="asis",fig.cap="Recruitment Y, panel indicate if selected"}
asis_output("# Recruitment series Y")
cat("\n")
g <- figure_yellow_recruitment()
glog<- g + scale_y_log10(limits=c(0.001,30),breaks=c(0.01,0.1,1,10,100,1000),
		labels=c("0.01","0.1","1","10","100","1000"))
gridExtra::grid.arrange(g+ggtitle("Natural Scale"),glog+ggtitle("Log Scale"),nrow=2)
cat("\n")
```


```{r yellow, echo=FALSE, warning=FALSE, results="asis",fig.cap="Recruitment Y, panel indicate if selected"}
asis_output("# Yellow standing stock series Y")
cat("\n")
g <- figure_ys(stage_selected = "Y")
print(g)
cat("\n")
```



```{r silver, echo=FALSE, warning=FALSE, results="asis",fig.cap="Silver series"}
asis_output("# Silver series S")
cat("\n")
g <- figure_ys(stage_selected = "S")
print(g)
cat("\n")
```


```{r mapr, echo=FALSE, warning=FALSE, results="asis",eval=params$map,fig.cap="Maps of recruitment time series (G+GY)"}
asis_output("# Maps of recruitment series (G + GY)")
cat("\n")
g <- map_recruitment()
print(g)
cat("\n")
```


```{r mapyr, echo=FALSE, warning=FALSE, results="asis",eval=params$map,fig.cap="Maps of recruitment time series (Y)"}
asis_output("# Maps of recruitment series (Y)\\n")
cat("\n")
g <- map_yellow_recruitment()
print(g)
cat("\n")
```



```{r mapy, echo=FALSE, warning=FALSE, results="asis",eval=params$map,fig.cap="Maps of Yellow (Y) and silver (S) time series"}
asis_output("# Maps of yellow (standing stock) and silver time series\\n")
cat("\n")
g <- map_ys()
print(g)
cat("\n")
```
