---
title: "Trend in fisheries"
author: "WGEEL"
date: "27 September 2021"
output: word_document
keep_md: yes
test: "`r paste('_metadata.yaml')`"
---
\newline
```{r setup, include=TRUE, echo=FALSE}
# replace word_document or html_document

#--------------------------------
# get your current name 
#--------------------------------
getUsername <- function(){
	name <- Sys.info()[["user"]]
	return(name)
}
#--------------------------------

#if (getUsername() == "hilaire.drouineau") setwd("~/Documents/Bordeaux/migrateurs/WGEEL/github/wg_WGEEL/R/Rmarkdown/")
#if (getUsername() == "cedric.briand") setwd("C:/workspace/gitwgeel/R/Rmarkdown") 
#if (getUsername() == "cboulenger") setwd("C:/Users/cboulenger/Documents/wg_WGEEL/R/Rmarkdown") 

CY=2022
library(stringr)
knitr::opts_chunk$set(echo = TRUE, warnings=FALSE, error = TRUE)
#source("R/utilities/set_directory.R")
#data_directory <- wg_choose.dir(caption = "Where do you want to save the tables and the graphs")
#data_directory <-"C:/temp"
#knitr::opts_knit$set(root.dir = data_directory)
render="docx"  # html 
# temporary file to store the variables (this is necessary to print the text)

# to test the output and adapt the type of table
output <- rmarkdown::metadata$output
```



```{r load_utilities, eval=TRUE, echo=FALSE,include=FALSE}

source("../utilities/load_library.R")

#-----------------
# other libraries
#-----------------
load_package("readxl")
load_package("getPass")
load_package("stringr")
load_package("reshape2")
load_package("tidyr") # unite cols in maps
load_package("rlang")
load_package("sp")
#load_package("pool")
#load_package("DBI")
load_package("RPostgreSQL")
load_package("dplyr")
load_package("RColorBrewer")
load_package("sqldf")
load_package("scales")
load_package('stringr') # text handling
#load_package("XLConnect") # for excel
load_package("ggplot2") # for excel
load_package("gridExtra")
load_package("colorspace")
load_package("ggrepel")
load_package("viridis")
load_package("svglite")
load_package("leaflet.minicharts")
load_package("glue")
load_package("kableExtra")
load_package("yaml")
load_package("RPostgres")
cred=read_yaml("../../credentials.yml")

# load functions ------------------------------------------------------------------------------------
# retrieve reference tables needed
# the shiny is launched from shiny_data_integration/shiny thus we need the ../
if(is.null(options()$sqldf.RPostgreSQL.user)){
	wd <- getwd()
	setwd("../shiny_data_visualisation/shiny_dv/")
	source("database_connection.R")
	setwd(wd)
}
con_wgeel = dbConnect(RPostgres::Postgres(), dbname=cred$dbname,host=cred$host,port=cred$port,user=cred$user, password=getPass())
#
#
biometry_group_data_series <- dbGetQuery(
		con_wgeel,
		"SELECT * FROM datawg.t_series_ser
				JOIN datawg.t_groupseries_grser  ON grser_ser_id = ser_id
				JOIN datawg.t_metricgroupseries_megser ON meg_gr_id = gr_id 
				LEFT JOIN ref.tr_metrictype_mty ON mty_id=meg_mty_id 
				")
biometry_group_data_sampling <- dbGetQuery(
		con_wgeel,
		"SELECT * FROM datawg.t_samplinginfo_sai 
				JOIN datawg.t_groupsamp_grsa  ON grsa_sai_id = sai_id
				JOIN datawg.t_metricgroupsamp_megsa ON meg_gr_id = gr_id 
				LEFT JOIN ref.tr_metrictype_mty ON mty_id=meg_mty_id 
				")
## download data from the database
biometry_individual_series <- dbGetQuery(con_wgeel,
		"SELECT  ser_nameshort, 
				ser_cou_code, 
				ser_x,ser_y,
				ser_emu_nameshort,
				ser_hty_code,
				ser_lfs_code,
				gea_name_en, 
				sam_samplingtype,
				ser_qal_id,
				t_fishseries_fiser.*					
				FROM datawg.t_series_ser 
				JOIN datawg.t_fishseries_fiser  ON ser_id=fiser_ser_id
				JOIN datawg.t_metricindseries_meiser ON mei_fi_id = fi_id
				LEFT JOIN ref.tr_metrictype_mty ON mty_id=mei_mty_id
				LEFT JOIN ref.tr_samplingtype_sam ON ser_sam_id=sam_id
				LEFT JOIN ref.tr_gear_gea	ON ser_sam_gear=gea_id")	
				
#biometry_individual_series %>% filter(fi_id!=421454)

biometry_individual_sampling=dbGetQuery(con_wgeel,
		"SELECT 
t_samplinginfo_sai.*,
cou_code, cou_order,
t_fishsamp_fisa.*,
mty_name,
t_metricindsamp_meisa.*
FROM
datawg.t_samplinginfo_sai
JOIN datawg.t_fishsamp_fisa ON sai_id=fisa_sai_id
JOIN datawg.t_metricindsamp_meisa ON mei_fi_id = fi_id
LEFT JOIN ref.tr_metrictype_mty ON mty_id=mei_mty_id
LEFT JOIN ref.tr_country_cou on sai_cou_code= cou_code
")



data_ind_series = biometry_individual_series %>% 
		pivot_wider(names_from = mty_name, values_from = mei_value)

data_ind_series$month<-format(data_ind_series$fi_date,"%m")

## individual sampling data

data_ind_samp = biometry_individual_sampling %>% 
		pivot_wider(names_from = mty_name, values_from = mei_value)

## total data

#total_individual= bind_rows(
#		data_ind_series %>% as_tibble() %>%
#				select(country, EMU = ser_emu_nameshort, year,month, lengthmm, weightg,eye_diam_meanmm, pectoral_lengthmm, ageyear,differentiated_proportion, female_proportion, habitat = ser_hty_code, life_stage = ser_lfs_code, gear = gea_name_en) %>%
#				mutate(source = "series"),
#		
#		data_ind_samp %>% as_tibble() %>%
#				mutate(commercial = str_detect(sai_samplingstrategy, "ommercial") | str_detect(sai_samplingstrategy, "CF")) %>%
#				select(country, EMU = ser_emu_nameshort, year,month, lengthmm, weightg,eye_diam_meanmm, pectoral_lengthmm, ageyear,differentiated_proportion, female_proportion, habitat = ser_hty_code, life_stage = fi_lfs_code, commercial) %>% mutate(gear = "unkonwn", source = "sampling") 
#)




dbDisconnect(con_wgeel)

biometry_group_data_series_long <- biometry_group_data_series %>% 
		select(-geom, -mty_id, -mty_min, -mty_max)  %>% 
		pivot_wider(names_from = mty_name, values_from = meg_value)

biometry_group_data_sampling_long <- biometry_group_data_sampling %>% 
		select( -mty_id, -mty_min, -mty_max)  %>% 
		pivot_wider(names_from = mty_name, values_from = meg_value)



```

