# general configuration for shiny
# 
# Authors: lbeaulaton Cedric
# FIRST THING : load maps_for_shiny.Rdata in your data/shapefiles/ git directory
#             : load files dataset.Rdata, glass_eel_yoy.Rdata, older.Rdata, statseries.Rdata
#             : generated by the recruitment.rnw script 

###############################################################################
# debug notes for Cedric ....
#setwd("C:/workspace\\wg_WGEEL\\R\\shiny_data_visualisation\\shiny_dv\\")
#setwd("C:/Users/cboulenger/Documents/wg_WGEEL/R/shiny_data_visualisation/shiny")

# A big dataset is stored there
#"C:\\workspace\\wgeeldata\\shp"
# Other dataset are there
#/wgeeldata/recruitment/2018/data
# they are not in version control, they will be dropped on the sharepoint
# they need to be copied to 
# WGEEL\data

# options("help_type"="html")
#source("set_directory.R")

# connection to database
# this is now in load_data_from_database.R
# source("R/database_interaction/database_connection.R")

source("load_library.R")
#-----------------
# shiny libraries
#-----------------
load_package("shiny")
load_package("shinyWidgets")
load_package("shinydashboard")
load_package("shinyjs")
load_package("shinyBS")
load_package("leaflet")
load_package("DT")
load_package("sf")
load_package("plotly")
load_package("leaflet.extras")
load_package("yaml")
load_package("shinydashboardPlus")
#-----------------
# other libraries
#-----------------
load_package("readxl")
load_package("shinybusy")
load_package("stringr")
load_package("reshape2")
load_package("tidyr") # unite cols in maps
load_package("rlang")
load_package("sp")
#library("pool")
#library("DBI")

load_package("dplyr")
load_package("RColorBrewer")

load_package("scales")
load_package('stringr') # text handling
#library("XLConnect") # for excel
load_package("ggplot2") # for excel
load_package("gridExtra")
load_package("colorspace")
load_package("ggrepel")
load_package("viridis")
load_package("svglite")
load_package("leaflet.minicharts")
#library("spsComps") # handle errors
#library("shinytoast")

# load functions ------------------------------------------------------------------------------------

# retrieve reference tables needed
# the shiny is launched from shiny_data_integration/shiny thus we need the ../
jscode <- "shinyjs.closeWindow = function() { window.close(); }"


source("preco_diagram.R")
source("graphs.R")
source("maps.R")
source("predict_missing.R")
source("filter_and_group_functions.R")


# loading datasets ---------------------------------------------------------------------

# this file is added to the ignore list, so ask for it in your own git before launching the app
load("data/maps_for_shiny.Rdata") 
# now data are generated by the script load_data_from_the_database.R
load("data/ref_and_eel_data.Rdata")

# save(landings, aquaculture, release, precodata, habitat_ref, lfs_code_base, country_ref,  file= "/data/dataset.Rdata")
# without connexion to a database use Rdata instead, ask to Cedric

# current year --------------------------------------------------------------------------------------
cred=read_yaml("./credentials.yml")

CY = as.numeric(format(Sys.time(), "%Y"))

# load data from recruitment ------------------------------------------------------------------------
# note : these data have been produced by the script recruitment_analysis.Rnw
#      : they must be installed manually in folder /data  as we don't store data
#      : in git.
load("data/recruitment/wger.Rdata")
load("data/recruitment/wger_init.Rdata") # before selection process
load("data/recruitment/statseries.Rdata")
load("data/recruitment/glass_eel_yoy.Rdata")
load("data/recruitment/older.Rdata")
load("data/recruitment/R_stations.Rdata")
load("data/recruitment/dat_ge.Rdata") ; # named dat_ge
load("data/recruitment/dat_ye.Rdata") ; # named dat_ye
dat_ye$area <- "Yellow"
load("data/recruitment/recruitment_models.Rdata") # named model_ge_area and model_older
   


# Color palettes ------------------------------------------------------------------------------------

#TODO create better colors

values=c(RColorBrewer::brewer.pal(12,"Set3"),
    RColorBrewer::brewer.pal(12, "Paired"), 
    RColorBrewer::brewer.pal(8,"Accent"),
    RColorBrewer::brewer.pal(8, "Dark2"))
color_countries = setNames(values,country_ref$cou_code)

#d<-data.frame(as.data.frame(color_countries),cou_code=unique(emu_cou$emu_cou_code))
#values2<-NULL
#for (cou in unique(emu_cou$emu_cou_code)){
#  if (nrow(emu_cou[emu_cou$emu_cou_code==cou,])==1){values2[d$cou_code==cou]<-d$color_countries[d$cou_code==cou]}
#}
#nrow(cou)

#pallet for emu
values2=c(RColorBrewer::brewer.pal(9,"Set1"),
          RColorBrewer::brewer.pal(11,"Spectral"),
          RColorBrewer::brewer.pal(11,"PuOr"),
          RColorBrewer::brewer.pal(8,"Set2"),
          RColorBrewer::brewer.pal(11,"PRGn"),
          RColorBrewer::brewer.pal(12,"Set3"),
          RColorBrewer::brewer.pal(11,"BrBG"),
          RColorBrewer::brewer.pal(9,"Greys"),
          RColorBrewer::brewer.pal(9,"RdPu"),
          RColorBrewer::brewer.pal(12, "Paired"), 
          RColorBrewer::brewer.pal(9,"PuRd"),
          RColorBrewer::brewer.pal(8,"Accent"),
          RColorBrewer::brewer.pal(11,"PiYG"),
          RColorBrewer::brewer.pal(7,"Pastel2"),
          RColorBrewer::brewer.pal(8, "Dark2"))

## values to use for emu

values2<-c("#276419","#377EB8","#BF5B17","#B2DF8A","#5E4FA2","#FEE08B","#F1E2CC","#D53E4F","#F7F7F7","#FDC086","#252525","#FFF7F3",
"#7570B3","#E08214","#7FC97F","#DD3497","#BEAED4","#B15928","#CE1256","#FC8D62","#9E0142","#FFFFFF","#E5C494","#969696",
"#6A3D9A","#E78AC3","#E7E1EF","#FDB462","#B2ABD2","#4DAF4A","#FFFF33","#ABDDA4","#B3DE69","#E6F5D0","#FDE0EF","#FFFF99",
"#FDB863","#C994C7","#BF812D","#67001F","#CAB2D6","#D95F02","#737373","#FF7F00","#5AAE61","#F6E8C3","#D9F0D3","#40004B",
"#E6F598","#4D9221","#B35806","#F768A1","#FFFFBF","#003C30","#000000","#FB8072","#B3E2CD","#3288BD","#49006A","#F7F7F7",
"#D4B9DA","#386CB0","#D9D9D9","#A6761D","#FFFFB3","#7A0177","#FA9FB5","#FFD92F","#FF7F00","#980043","#F4CAE4","#DE77AE",
"#DFC27D","#F5F5F5","#BC80BD","#8DD3C7","#8073AC","#B3B3B3","#8DA0CB","#525252","#BEBADA","#66C2A5","#E7298A","#FCCDE5",
"#D8DAEB","#7F3B08","#666666","#E31A1C","#FFFF99","#FFF2AE","#C7EAE5","#E6AB02","#CCEBC5","#999999","#543005","#FDBF6F",
"#CBD5E8","#2D004B","#E7298A","#542788","#F7F7F7","#A6D854","#F0F0F0","#00441B","#33A02C","#1F78B4","#FB9A99","#E6F5C9",
"#7FBC41","#A65628","#B8E186","#A6CEE3","#A6DBA0","#FFED6F","#AE017E","#D9D9D9","#80CDC1","#C51B7D","#BDBDBD","#F7F4F9",
"#FDE0DD","#1B9E77","#FCC5C0","#FEE0B6","#80B1D3","#DF65B0","#C2A5CF","#9970AB","#66A61E","#F46D43","#1B7837","#E41A1C",
"#F1B6DA","#35978F","#FDCDAC","#8C510A","#8E0152","#FDAE61","#01665E","#E7D4E8","#F0027F","#66C2A5","#984EA3","#F781BF",
"#666666","#762A83")
color_emu = setNames(values2,emu_cou$emu_nameshort)


