---
title: "WKEMP_2021"
author: "Partal N."
date: "01 12 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE,message=FALSE)
```




```{r message=TRUE, warning=TRUE, include=FALSE}

library(dplyr)
library(ggrepel)
library(viridis)
library(stringr)
library(vegan)
library(sf)

library(RPostgres)
library(getPass)
library(tidyverse)
library(yaml)
cred=read_yaml("../../credentials.yml")
con = dbConnect(Postgres(), dbname=cred$dbname,host=cred$host,port=cred$port,user=cred$user, password=getPass())

precodata_all=dbGetQuery(con,"select * from datawg.precodata_all")
dbDisconnect(con)


```



## Draw the eel precautionary diagram
 


```{r message=FALSE, warning=FALSE}


#' @title Draw background of the precautionary diagram
background2<-function(Aminimum=0,Amaximum=6.5,Bminimum=1e-2,Bmaximum=1){
  # the left of the graph is filled with polygons
  Bminimum<<-Bminimum
  Bmaximum<<-Bmaximum
  Amaximum<<-Amaximum
  Aminimum<<-Aminimum
  B<-seq(Bminimum,0.4, length.out=30)
  Amgt<-0.92
  Btrigger=0.4
  SumA<-Amgt*(B/Btrigger) # linear decrease in proportion to B/Btrigger
  X<-c(B,rev(B))
  Ylowersquare<-c(SumA,rep(Aminimum,length(B)))
  df<-data.frame("B"=X,"SumA"=Ylowersquare,"color"="orange")
  Yuppersquare<-c(SumA,rep(Amaximum,length(B)))
  df<-rbind(df, data.frame("B"=X,"SumA"=Yuppersquare,"color"="red"))
  df<-rbind(df,data.frame("B"=c(0.4,0.4,Bmaximum,Bmaximum),"SumA"=c(Aminimum,0.94,0.94,Aminimum),"color"="green")) # drawn clockwise from low left corner
  df<-rbind(df,data.frame("B"=c(0.4,0.4,Bmaximum,Bmaximum),"SumA"=c(0.94,Amaximum,Amaximum,0.94),"color"="orange1")) # drawn clockwise from low left corner
  return(df)
}

#' @title Draw precautionary diagram itself
#' @param precodata data.frame with column being: eel_emu_nameshort	bcurrent	bbest	b0	suma, using extract_precodata()
#' @examples
#' x11()
#' trace_precodiag(extract_precodata())
# TODO: offer the possibility to aggregate by country
trace_precodiag3 = function(precodata, 
                            precodata_choice=c("emu","country","all"), 
                            last_year=TRUE,
                            years)
{  
  ###############################
  # Data selection
  # this in done on precodata which is filtered by the app using filter_data
  #############################
  precodata$last_year[is.na(precodata$last_year)] <- precodata$eel_year[is.na(precodata$last_year)]
  if (last_year) precodata <- precodata[precodata$last_year==precodata$eel_year ,]
  precodata <- precodata %>%
    filter(eel_year %in% years)
  
  if (length(precodata_choice) >1 ) title= "Precautionary diagram" else
    switch(precodata_choice,
           "emu"={title <- "Precautionary diagram for emu"},
           "country"={title <- "Precautionary diagram for country"},
           "country_bis"={title <- "Precautionary diagram for country"},
           "all"={title <- "Precautionary diagram for all countries"},
    )
  
  precodata<-unique(precodata[precodata$aggreg_level%in%precodata_choice,])
  ############################
  # Data for buble plot 
  ############################
  mylimits=c(0,1000)
  precodata$pSpR=exp(-precodata$suma)
  precodata$pbiom=precodata$ratio_bcurrent_b0
  if (any(precodata$bcurrent>precodata$b0,na.rm=TRUE)){
    cat("You  have Bbest larger than B0, you should check \n")
    Bmaximum<-max(precodata$pbiom,na.rm=TRUE)
  } else Bmaximum=1
  if (any(is.na(precodata$b0))) cat("Be careful, at least some B0 are missing")
  if (max(precodata$bbest,na.rm=TRUE)>mylimits[2]) mylimits[2]<-max(precodata$bbest,na.rm=TRUE)
  if (all(is.na(precodata$pbiom))|all(is.na(precodata$pSpR))) errortext<-"Missing data" else errortext<-""
  df<-background2(Aminimum=0,Amaximum=5,Bminimum=exp(-5),Bmaximum=Bmaximum)
  ######################
  # Drawing the graphs
  ############################
  # If EMU only show labels
  if (length(precodata_choice)==1){    
    choose_label_for_plot <- rep(TRUE,length(precodata))
    choose_color <- "eel_year"
    
    
  } else {
    
    choose_label_for_plot <- precodata$aggreg_level != "emu"
    choose_color <- "aggreg_level"
  }
  precodata$eel_year <- as.factor(precodata$eel_year)
  if (precodata_choice == "emu"){
    labels <- precodata$eel_emu_nameshort
  } else {
    labels <- precodata$eel_cou_code
  }
  g<- ggplot(df)+
    theme_bw()+
    theme(legend.key = element_rect(colour = "white"))+
    geom_polygon(aes(x=B,y=SumA,fill=color),alpha=0.7)+
    scale_fill_identity(labels=NULL)+
    scale_x_continuous(name=expression(paste(bold("Spawner escapement")~ ~over(B,B0))),
                       limits=c(Bminimum, Bmaximum),trans="log10",
                       breaks=c(0.005,0.01,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1),
                       labels=c("","1%","5%","10%","","","40%","","","","","","100%"))+ 
    scale_y_continuous(name=expression(paste(bold("Lifetime mortality")~ ~symbol("\123"),"A")),
                       limits=c(Aminimum, Amaximum)) +
    #geom_path(data = precodata,aes(x = pbiom, y = suma, group = eel_cou_code))+
    #scale_color_discrete(#guide = 'none'
    #    ) +
    geom_point(data=precodata,aes_string(x="pbiom",y="suma",size="bbest",color=choose_color), alpha=0.7)+ 
    geom_text_repel(data=precodata, aes(x=pbiom,
                                        y = suma,
                                        label = labels#,
                                        #size=bbest/8
    ),
    show.legend = FALSE      
    )+
    scale_size(name="B best (millions)",range = c(2, 25),limits=c(0,max(pretty(precodata$bbest))))+
    annotate("text",x =  1, y = 0.92, label = "0.92",  parse = F, hjust=1,vjust=-1.1, size=3)+
    annotate("text",x =  1, y = 0.92, label = "Amgt",  parse = F, hjust=1,vjust=1.1, size=3)+
    annotate("text",x =  0.4, y = 0, label = "Bmgt",  parse = F, hjust=0,vjust=-0.7, size=3,angle=90)+
    annotate("text",x =  0.4, y = 0, label = "Btrigger",  parse = F, hjust=0,vjust=1.1, size=3,angle=90)+
    #annotate("text",x =  0.1, y = 2, label = errortext,  parse = F, hjust=1,vjust=1, size=5,col="white")+
    annotate("text",x =  Bminimum, y = 0, label = "100% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = 1.2, label = "30% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = 1.6, label = "20% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = 2.3, label = "10% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = 2.99, label = "5% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = 4.6, label = "1% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = Amaximum, label = "%SPR",  parse = F, hjust=1,vjust=-3,size=3,angle=90)+               
    ggtitle(str_c(title))
  if(pretty(max(precodata$suma,na.rm=TRUE))[2] > 4.6)   g = g +annotate("text",x =  Bminimum, y = 4.6, label = "1%",  parse = F, hjust=1, size=3) 
  if (choose_color == "eel_year")
    g+scale_colour_viridis(discrete=TRUE) else
      g+scale_colour_brewer(palette = "Set3",direction=-1)
  
  
  return(g)
}


```


## Precautionary diagrams for countries in 2020.

```{r message=FALSE, warning=FALSE}

trace_precodiag3(precodata_all,"country",last_year=2020,years=2020)

```


## Precautionary diagrams for countries in 2019.

```{r message=TRUE, warning=TRUE}

trace_precodiag3(precodata_all,"country",last_year=FALSE,years=2019)

```


## Precautionary diagrams for countries in 2018.

```{r message=TRUE, warning=TRUE}

trace_precodiag3(precodata_all, "country", last_year = FALSE, years = 2018)

```


## Precautionary diagrams for emu's in 2020.

```{r message=FALSE, warning=FALSE}

trace_precodiag3(precodata_all,"emu",last_year=2020,years=2020)

```


## Precautionary diagrams for emu's in 2019.

```{r message=FALSE, warning=FALSE}

trace_precodiag3(precodata_all,"emu",last_year=FALSE,years=2019)

```


## Precautionary diagrams for emu's in 2018.

```{r message=FALSE, warning=FALSE}

trace_precodiag3(precodata_all, "emu", last_year = FALSE, years = 2018)

```



## Precautionary diagrams for adjusted B0.



```{r message=FALSE, warning=FALSE, include=FALSE}

#source("readingAnnex13.R") # run above and save the annex13.Rdata in data_dependencies if this fails
load( file=file.path(getwd(),"data_dependencies","annex13.Rdata")) 
load("../../R/shiny_data_visualisation/shiny_dv/data/maps_for_shiny.Rdata")
load("../../R/shiny_data_visualisation/shiny_dv/data/recruitment/dat_ge.Rdata")
load("../../R/shiny_data_visualisation/shiny_dv/data/recruitment/dat_ye.Rdata")


eu_cou_codes=c("AT",	"BE",	"BG",	"HR",	"CY",	"CZ",	"DK",	"EE",	"FI",	"FR",	"DE",	"GR",	"HU",	"IE",	"IT",	"LV",	"LT",	"LU",	"MT",	"NL",	"PL",	"PT",	"RO",	"SK",	"SI",	"ES",	"SE",	"GB")

emu_sea= emu_p %>%
  filter(emu_cou_code %in% eu_cou_codes) %>%
  mutate(rec_zone = ifelse(emu_cou_code %in% c("NL","DK","NO","BE","LU", "CZ","SK") |
                             emu_nameshort %in% c("FR_Rhin","FR_Meus","GB_Tham","GB_Angl","GB_Humb","GB_Nort","GB_Solw",
                                                  "DE_Ems","DE_Wese","DE_Elbe","DE_Rhei","DE_Eide","DE_Maas") ,
                           "NS", 
                           ifelse(emu_cou_code %in% c("EE","FI","SE","LV","LT","AX", "PL","DE"),
                                  "BA",
                                  "EE")))


library(yaml)
cred=read_yaml("../../credentials.yml")
con = dbConnect(Postgres(), dbname=cred$dbname,host=cred$host,port=cred$port,user=cred$user, password=getPass())
precodata_all=dbGetQuery(con,"select * from datawg.precodata_all")
dbDisconnect(con)


mor_wise = annexes13_method %>% select(emu_nameshort,mortality_wise)
mor_wise = merge(emu_sea %>% st_drop_geometry(),mor_wise)
mor_wise <- mor_wise %>% 
  mutate(cohort_wise=grepl("ohort",mortality_wise)) %>%
  mutate(emu_nameshort=ifelse(emu_nameshort=="NL_Neth", "NL_total",emu_nameshort))
precodata_all=precodata_all %>% left_join(mor_wise,by=c("eel_emu_nameshort"="emu_nameshort"))


```




```{r message=FALSE, warning=FALSE, include=FALSE}


estimate_b0 = function(emu, year, mor_wise,precodata){
  print(emu)
  mod = switch(unique(mor_wise$rec_zone[mor_wise$emu_nameshort == emu]),
               "EE" = dat_ge %>% filter (area == "Elsewhere Europe"),
               "NS" = dat_ge %>% filter (area == "North Sea"),
               "BA" = dat_ye)
  if ("value_std_1960_1979" %in% names(mod)){
    Rcurrent <- mean(mod$value_std_1960_1979[mod$year %in% ((year-4):year)])
  } else {
    Rcurrent <- mean(mod$p_std_1960_1979[mod$year %in% ((year-4):year)])
  }
  if (unique(mor_wise$cohort_wise[mor_wise$emu_nameshort==emu]))
    Rcurrent <- switch(mor_wise$rec_zone[mor_wise$emu_nameshort == emu],
                       "EE" = mean(mod$p_std_1960_1979[mod$year %in% ((year-12):(year-7))]),
                       "NS" = mean(mod$p_std_1960_1979[mod$year %in% ((year-17):(year-12))]),
                       "BA" = mean(mod$value_std_1960_1979[mod$year %in% ((year-22):(year-17))]))
  precodata$bbest[precodata$eel_emu_nameshort==emu & precodata$eel_year==year] / Rcurrent
}
  
  

```



```{r message=FALSE, warning=FALSE, include=FALSE}



#' @title Draw background of the precautionary diagram
background2<-function(Aminimum=0,Amaximum=6.5,Bminimum=1e-2,Bmaximum=1){
  # the left of the graph is filled with polygons
  Bminimum<<-Bminimum
  Bmaximum<<-Bmaximum
  Amaximum<<-Amaximum
  Aminimum<<-Aminimum
  B<-seq(Bminimum,0.4, length.out=30)
  Amgt<-0.92
  Btrigger=0.4
  SumA<-Amgt*(B/Btrigger) # linear decrease in proportion to B/Btrigger
  X<-c(B,rev(B))
  Ylowersquare<-c(SumA,rep(Aminimum,length(B)))
  df<-data.frame("B"=X,"SumA"=Ylowersquare,"color"="orange")
  Yuppersquare<-c(SumA,rep(Amaximum,length(B)))
  df<-rbind(df, data.frame("B"=X,"SumA"=Yuppersquare,"color"="red"))
  df<-rbind(df,data.frame("B"=c(0.4,0.4,Bmaximum,Bmaximum),"SumA"=c(Aminimum,0.94,0.94,Aminimum),"color"="green")) # drawn clockwise from low left corner
  df<-rbind(df,data.frame("B"=c(0.4,0.4,Bmaximum,Bmaximum),"SumA"=c(0.94,Amaximum,Amaximum,0.94),"color"="orange1")) # drawn clockwise from low left corner
  return(df)
}

#' @title Draw precautionary diagram itself
#' @param precodata data.frame with column being: eel_emu_nameshort	bcurrent	bbest	b0	suma, using extract_precodata()
#' @examples
#' x11()
#' trace_precodiag(extract_precodata())
# TODO: offer the possibility to aggregate by country
trace_precodiag3 = function(precodata, 
                            precodata_choice=c("emu","country","all"), 
                            last_year=TRUE,
                            years)
{  
  ###############################
  # Data selection
  # this in done on precodata which is filtered by the app using filter_data
  #############################
  precodata$last_year[is.na(precodata$last_year)] <- precodata$eel_year[is.na(precodata$last_year)]
  if (last_year) precodata <- precodata[precodata$last_year==precodata$eel_year ,]
  precodata <- precodata %>%
    filter(eel_year %in% years)
  
  if (length(precodata_choice) >1 ) title= "Precautionary diagram" else
    switch(precodata_choice,
           "emu"={title <- "Precautionary diagram for emu"},
           "country"={title <- "Precautionary diagram for country"},
           "country_bis"={title <- "Precautionary diagram for country"},
           "all"={title <- "Precautionary diagram for all countries"},
    )
  
  precodata<-unique(precodata[precodata$aggreg_level%in%precodata_choice,])
  ############################
  # Data for buble plot 
  ############################
  mylimits=c(0,1000)
  precodata$pSpR=exp(-precodata$suma)
  precodata$pbiom=precodata$bcurrent / mapply(estimate_b0, precodata$eel_emu_nameshort, precodata$eel_year,
                                              MoreArgs=list(mor_wise = mor_wise,
                                                            precodata = precodata))
  if (any(precodata$bcurrent>precodata$b0,na.rm=TRUE)){
    cat("You  have Bbest larger than B0, you should check \n")
    Bmaximum<-max(precodata$pbiom,na.rm=TRUE)
  } else Bmaximum=1
  if (any(is.na(precodata$b0))) cat("Be careful, at least some B0 are missing")
  if (max(precodata$bbest,na.rm=TRUE)>mylimits[2]) mylimits[2]<-max(precodata$bbest,na.rm=TRUE)
  if (all(is.na(precodata$pbiom))|all(is.na(precodata$pSpR))) errortext<-"Missing data" else errortext<-""
  df<-background2(Aminimum=0,Amaximum=5,Bminimum=exp(-5),Bmaximum=Bmaximum)
  ######################
  # Drawing the graphs
  ############################
  # If EMU only show labels
  if (length(precodata_choice)==1){    
    choose_label_for_plot <- rep(TRUE,length(precodata))
    choose_color <- "eel_year"
    
    
  } else {
    
    choose_label_for_plot <- precodata$aggreg_level != "emu"
    choose_color <- "aggreg_level"
  }
  precodata$eel_year <- as.factor(precodata$eel_year)
  if (precodata_choice == "emu"){
    labels <- precodata$eel_emu_nameshort
  } else {
    labels <- precodata$eel_cou_code
  }
  g<- ggplot(df)+
    theme_bw()+
    theme(legend.key = element_rect(colour = "white"))+
    geom_polygon(aes(x=B,y=SumA,fill=color),alpha=0.7)+
    scale_fill_identity(labels=NULL)+
    scale_x_continuous(name=expression(paste(bold("Spawner escapement")~ ~over(B,B0))),
                       limits=c(Bminimum, Bmaximum),trans="log10",
                       breaks=c(0.005,0.01,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1),
                       labels=c("","1%","5%","10%","","","40%","","","","","","100%"))+ 
    scale_y_continuous(name=expression(paste(bold("Lifetime mortality")~ ~symbol("\123"),"A")),
                       limits=c(Aminimum, Amaximum)) +
    #geom_path(data = precodata,aes(x = pbiom, y = suma, group = eel_cou_code))+
    #scale_color_discrete(#guide = 'none'
    #    ) +
    geom_point(data=precodata,aes_string(x="pbiom",y="suma",size="bbest",color=choose_color), alpha=0.7)+ 
    geom_text_repel(data=precodata, aes(x=pbiom,
                                        y = suma,
                                        label = labels#,
                                        #size=bbest/8
    ),
    show.legend = FALSE      
    )+
    scale_size(name="B best (millions)",range = c(2, 25),limits=c(0,max(pretty(precodata$bbest))))+
    annotate("text",x =  1, y = 0.92, label = "0.92",  parse = F, hjust=1,vjust=-1.1, size=3)+
    annotate("text",x =  1, y = 0.92, label = "Amgt",  parse = F, hjust=1,vjust=1.1, size=3)+
    annotate("text",x =  0.4, y = 0, label = "Bmgt",  parse = F, hjust=0,vjust=-0.7, size=3,angle=90)+
    annotate("text",x =  0.4, y = 0, label = "Btrigger",  parse = F, hjust=0,vjust=1.1, size=3,angle=90)+
    #annotate("text",x =  0.1, y = 2, label = errortext,  parse = F, hjust=1,vjust=1, size=5,col="white")+
    annotate("text",x =  Bminimum, y = 0, label = "100% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = 1.2, label = "30% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = 1.6, label = "20% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = 2.3, label = "10% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = 2.99, label = "5% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = 4.6, label = "1% -",  parse = F, hjust=1, size=3)+
    annotate("text",x =  Bminimum, y = Amaximum, label = "%SPR",  parse = F, hjust=1,vjust=-3,size=3,angle=90)+               
    ggtitle(str_c(title))
  if(pretty(max(precodata$suma,na.rm=TRUE))[2] > 4.6)   g = g +annotate("text",x =  Bminimum, y = 4.6, label = "1%",  parse = F, hjust=1, size=3) 
  if (choose_color == "eel_year")
    g<- g+scale_colour_viridis(discrete=TRUE) else
    g<-g+scale_colour_brewer(palette = "Set3",direction=-1)
  
  
  
  return(g)
}


```





```{r echo=FALSE, message=FALSE, warning=FALSE}
trace_precodiag3(precodata_all %>% filter(eel_emu_nameshort %in% mor_wise$emu_nameshort),"emu",last_year=FALSE,years=2020)
```




```{r echo=FALSE, message=FALSE, warning=FALSE}

trace_precodiag3(precodata_all %>% filter(eel_emu_nameshort %in% mor_wise$emu_nameshort),"emu",last_year=FALSE,years=2019)

```




```{r echo=FALSE, message=FALSE, warning=FALSE}

trace_precodiag3(precodata_all %>% filter(eel_emu_nameshort %in% mor_wise$emu_nameshort),"emu",last_year=TRUE,years=2018)

```

