---
title: "biometry_individual"
author: "ICES Data Group"
date: "12/09/2022"
bibliography: biometry.bib
csl: "../Rmarkdown/ices-journal-of-marine-science.csl"
output: 
  bookdown::word_document2:
    fig_caption: yes
    number_sections: yes
    reference_docx: "../Rmarkdown/ICES_template.docx"
---

```{r setup, include=FALSE}
source("../utilities/load_library.R")


knitr::opts_chunk$set(echo = TRUE,warning=FALSE,message=FALSE,error=FALSE,fig.width=14.9/2.54,dpi=150)
load_library("readxl")
load_library("sf")
load_library("rnaturalearth")
load_library("getPass")
load_library("dplyr")
load_library("ggplot2")
load_library("Kendall")
load_library("RPostgres")
load_library("ggmap")
load_library("hues")
load_library("RPostgres")
load_library("flextable")
load_library("yaml")
load_library("tidyr")
load_library("lubridate")
load_library("stringr")
load_library("quantreg")


if(Sys.info()["user"]=="hilaire.drouineau"){
  allometry=read_excel("~/Bureau/slopesintercepts.xlsx")
  setwd("~/Documents/Bordeaux/migrateurs/WGEEL/github/wg_WGEEL/R/biometry_analysis/")
}
colorpalette=cbf_1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
           "#F0E442", "#0072B2", "#D55E00", "#CC79A7")



cred=read_yaml("../../credentials.yml")
con_wgeel = dbConnect(Postgres(), dbname=cred$dbname,host=cred$host,port=cred$port,user=cred$user, password=getPass())

## download data from the database
biometry_individual_series=dbGetQuery(con_wgeel,"with sel as(SELECT d.*, t_series.*, mty_name FROM datawg.t_metricindseries_meiser d, datawg.t_fishseries_fiser t_series, ref.tr_metrictype_mty WHERE mty_id=mei_mty_id AND mei_fi_id = fi_id) 
select sel.*, ser_nameshort, ser_cou_code, ser_x,ser_y,ser_emu_nameshort, ser_hty_code,ser_lfs_code,gea_name_en, sam_samplingtype,t_series_ser.ser_qal_id from sel, datawg.t_series_ser, ref.tr_gear_gea, ref.tr_samplingtype_sam where ser_id=fiser_ser_id and ser_sam_gear=gea_id and ser_sam_id=sam_id")

biometry_individual_series<-biometry_individual_series %>% filter(fi_id!=421454)

biometry_individual_sampling=dbGetQuery(con_wgeel,"with sel as(SELECT d.*, t_samp.*, mty_name FROM datawg.t_metricindsamp_meisa d, datawg.t_fishsamp_fisa t_samp, ref.tr_metrictype_mty WHERE mty_id=mei_mty_id AND mei_fi_id = fi_id) 
select * from sel, datawg.t_samplinginfo_sai where sai_id=fisa_sai_id")

cou_ref=dbGetQuery(con_wgeel,"select cou_code, cou_order from ref.tr_country_cou")
cou_ref= cou_ref[order(cou_ref$cou_order), ]

values=c(RColorBrewer::brewer.pal(12,"Set3"),
    RColorBrewer::brewer.pal(12, "Paired"), 
    RColorBrewer::brewer.pal(8,"Accent"),
    RColorBrewer::brewer.pal(8, "Dark2"))
color_countries = setNames(values,cou_ref$cou_code)

## preparing the data to be exploited

  ## individual series

data_ind_series = biometry_individual_series %>% 
	select(ser_id = fiser_ser_id, year = fi_year,date=fi_date,  fi_id, country=ser_cou_code, comment = fi_comment, quality = mei_qal_id, mty_name, mei_value,ser_nameshort, ser_x,ser_y,ser_emu_nameshort, ser_hty_code,ser_lfs_code, gea_name_en, sam_samplingtype,ser_qal_id) %>%
	pivot_wider(names_from = mty_name, values_from = mei_value)

data_ind_series$ser_lfs_code=factor(as.character(data_ind_series$ser_lfs_code),levels=c("G","GY","Y","S"))
data_ind_series$month<-format(data_ind_series$date,"%m")
data_ind_series$country<-factor(data_ind_series$country,levels=cou_ref$cou_code,ordered=TRUE)

  ## individual sampling data

data_ind_samp = biometry_individual_sampling %>% 
	select(ser_id = fisa_sai_id, year = fi_year, date=fi_date,  fi_id=mei_fi_id, fi_x=fisa_x_4326, fi_y=fisa_y_4326, fi_lfs_code, country=sai_cou_code, comment = fi_comment, quality = mei_qal_id, mty_name, mei_value,ser_nameshort=sai_name,ser_emu_nameshort=sai_emu_nameshort, ser_hty_code=sai_hty_code,sai_samplingstrategy) %>%
	pivot_wider(names_from = mty_name, values_from = mei_value)

data_ind_samp$fi_lfs_code=factor(as.character(data_ind_samp$fi_lfs_code),levels=c("G","GY","Y","YS","S"))
data_ind_samp$month<-format(data_ind_samp$date,"%m")
data_ind_samp$country<-factor(data_ind_samp$country,levels=cou_ref$cou_code,ordered=TRUE)

    ## total data

total_individual= bind_rows(
	data_ind_series %>% as_tibble() %>%
		select(country, EMU = ser_emu_nameshort, year,month, lengthmm, weightg,eye_diam_meanmm, pectoral_lengthmm, ageyear,differentiated_proportion, female_proportion, habitat = ser_hty_code, life_stage = ser_lfs_code, gear = gea_name_en) %>%
		mutate(source = "series"),

	data_ind_samp %>% as_tibble() %>%
		mutate(commercial = str_detect(sai_samplingstrategy, "ommercial") | str_detect(sai_samplingstrategy, "CF")) %>%
		select(country, EMU = ser_emu_nameshort, year,month, lengthmm, weightg,eye_diam_meanmm, pectoral_lengthmm, ageyear,differentiated_proportion, female_proportion, habitat = ser_hty_code, life_stage = fi_lfs_code, commercial) %>% mutate(gear = "unkonwn", source = "sampling") 
)%>% 
	mutate(length_class_cm = as.integer(as.character(cut(lengthmm, breaks = seq(0, 1350, 10), labels = seq(0, 1340, 10) + 5)))/10)


total_individual$country<-factor(total_individual$country,levels=cou_ref$cou_code,ordered=TRUE)

 dbDisconnect(con_wgeel)

```

# Raw data 

The table describes the available individual biometric data from Appendix 1,2,3 (series) and 10 (sampling) 


```{r available_data, include }
stats_data= total_individual %>% group_by(source,country,EMU,habitat,life_stage) %>%
  summarize(
            n_lengthmm=(sum(!is.na(lengthmm))),
            n_bio_weight=(sum(!is.na(weightg))),
            n_female_proportion=(sum(!is.na(female_proportion))),
            n_pectoral_length=(sum(!is.na(pectoral_lengthmm))),
            n_eye_diam_meanmm=(sum(!is.na(eye_diam_meanmm))),
            n_ageyear=(sum(!is.na(ageyear))),
            n_differentiated_proportion=(sum(!is.na(differentiated_proportion)))) %>%
  filter((n_lengthmm+n_bio_weight+n_female_proportion+n_pectoral_length+n_eye_diam_meanmm+n_ageyear+n_differentiated_proportion)>0) %>%
  arrange(source,life_stage,country,habitat,EMU)
autofit(flextable(stats_data))

```
```{r decriptivegraphs, include=TRUE}

## length frequency

	ggplot(total_individual) + aes(x = length_class_cm, color = life_stage) +
	geom_density() + facet_grid(life_stage ~commercial, scales = "free_y")

## length by month

p <- ggplot(total_individual, aes(month,lengthmm))
p + geom_boxplot()+ facet_grid(vars(source),vars(life_stage), scales = "free_y")




```

```{r lengthweightlfs, include=TRUE}

## lfs effect on size-weight

ggplot(total_individual,aes(x=lengthmm,y=weightg))+geom_point()+
  facet_grid(vars(life_stage), vars(source),scale="free")+
  theme_bw()+xlab("Length (mm)")+ylab("Weight (g)")


```
```{r lengthweightrelationship, include=TRUE}

# all data

## prepare the data
reg_series_data<-total_individual[!is.na(total_individual$weightg) & !is.na(total_individual$lengthmm),]
reg_series_data<-total_individual[total_individual$weightg>0 & total_individual$lengthmm>100,]
reg_series_data<-reg_series_data[reg_series_data$life_stage %in% c("Y","S") & !is.na(reg_series_data$life_stage),]

reg_series_data$country<-factor(reg_series_data$country,levels=cou_ref$cou_code,ordered=TRUE)


reg_w_series = rq(log(reg_series_data$weightg)~log(reg_series_data$lengthmm), tau= 0.75)

summary(reg_w_series)

#calcul de Ws
reg_series_data$ws = exp(predict(reg_w_series, newdata = reg_series_data))

#calcul de Wr
reg_series_data$wr = reg_series_data$weightg / reg_series_data$ws *100


## regression with all data

p <- ggplot(reg_series_data, aes(lengthmm, ws))
p + geom_point(aes(lengthmm,weightg, colour=life_stage))+ geom_line()

## representation of the results with all data

p <- ggplot(reg_series_data, aes(lengthmm, wr, colour=life_stage))
p + geom_point()+ geom_hline(yintercept = c(25,200))

n_total<-nrow(reg_series_data)

n_inconsistent<-nrow(reg_series_data[reg_series_data$wr<25 | reg_series_data$wr>200,])

## boxplot of the resultat with only consistant data

reg_data_cons<-reg_series_data[reg_series_data$wr>25 & reg_series_data$wr<200,]

p <- ggplot(reg_data_cons, aes(country, wr, fill=country))
p + geom_boxplot()+ scale_fill_manual(values=color_countries[names(color_countries) %in% unique(reg_series_data$country)], drop = TRUE)+geom_hline(yintercept =100) + facet_grid(vars(source),vars(life_stage))



head(reg_series_dataY[is.na(reg_series_dataY$wr),])




```



```{r rawdata, include=TRUE}


data_ind_seriesG<-data_ind_series[data_ind_series$ser_lfs_code=="G",]
data_ind_seriesGY<-data_ind_series[data_ind_series$ser_lfs_code=="GY",]
data_ind_seriesY<-data_ind_series[data_ind_series$ser_lfs_code=="Y",]
data_ind_seriesS<-data_ind_series[data_ind_series$ser_lfs_code=="S",]


## Gear effect on size-weight

ggplot(data_ind_seriesG,aes(x=lengthmm,y=weightg))+geom_point()+
  facet_grid(vars(gea_name_en))+
  theme_bw()+ggtitle("Glass eel")+xlab("Length (mm)")+ylab("Weight (g)")

ggplot(data_ind_seriesY,aes(x=lengthmm,y=weightg))+geom_point()+
  facet_grid(vars(gea_name_en))+
  theme_bw()+ggtitle("Yellow")+xlab("Length (mm)")+ylab("Weight (g)")

ggplot(data_ind_seriesS,aes(x=lengthmm,y=weightg))+geom_point()+
  facet_grid(vars(gea_name_en))+
  theme_bw()+ggtitle("Silver")+xlab("Length (mm)")+ylab("Weight (g)")

## lfs effect on size-weight


ggplot(data_ind_series,aes(x=lengthmm,y=weightg))+geom_point()+
  facet_wrap(.~ser_lfs_code,scale="free")+
  theme_bw()+ggtitle("mixed")+xlab("Length (mm)")+ylab("Weight (g)")


## length by gear and year


stat_length_g<-data_ind_seriesG %>%
    group_by(year,gea_name_en,country) %>%
    dplyr::summarize(Mean = mean(weightg, na.rm=TRUE), sd=sd(weightg,na.rm=TRUE))

stat_length_y<-data_ind_seriesY %>%
    group_by(year,gea_name_en,country) %>%
    dplyr::summarize(Mean = mean(lengthmm, na.rm=TRUE), sd=sd(lengthmm,na.rm=TRUE))

ggplot(stat_length_g, aes(year, Mean))+ geom_pointrange(aes(ymin = Mean-sd, ymax = Mean+sd))+ 
  facet_grid(vars(gea_name_en),vars(country)) + theme_bw()+xlab("Year")+ylab("Mean length (mm)") +ggtitle("Glass eel")

ggplot(stat_length_y, aes(year, Mean))+ geom_pointrange(aes(ymin = Mean-sd, ymax = Mean+sd))+ 
  facet_grid(vars(country),vars(gea_name_en)) + theme_bw()+xlab("Year")+ylab("Mean length (mm)") +ggtitle("Yellow eel")







ggplot(data,aes(x=lengthmm,y=lengthmm))+geom_point()+
  facet_wrap(.~ser_lfs_code,scale="free")+
  theme_bw()+ggtitle("male")+xlab("Length (mm)")+ylab("Weight (g)")
ggplot(data,aes(x=lengthmm_f,y=bio_weight_f))+geom_point()+
  facet_wrap(.~ser_lfs_code,scale="free")+
  theme_bw()+ggtitle("female")+xlab("Length (mm)")+ylab("Weight (g)")



stat_length_g<-data_y %>%
    group_by(year,gea_name_en,ser_emu_nameshort) %>%
    dplyr::summarize(Mean = mean(lengthmm, na.rm=TRUE), sd=sd(lengthmm,na.rm=TRUE))

ggplot(stat_length_g, aes(year, Mean))+ geom_pointrange(aes(ymin = Mean-sd, ymax = Mean+sd))+ 
  facet_grid(vars(gea_name_en),vars(ser_emu_nameshort)) + theme_bw()+xlab("Year")+ylab("Mean length (mm)") +ggtitle("Glass eel")

ggplot(stat_length_g, aes(year, Mean, colour=ser_emu_nameshort))+ geom_pointrange(aes(ymin = Mean-sd, ymax = Mean+sd))+ 
  facet_grid(vars(gea_name_en)) + theme_bw()+xlab("Year")+ylab("Mean length (mm)") +ggtitle("Glass eel")




```

