### MARSS

```{r load libraries, include=FALSE}
source("../../utilities/load_library.R")
load_library("MARSS")
load_library("gridExtra")
load_library("xtable")
load_library("getPass")
load_library("RPostgres")
load_library("sf")
load_library("flextable")
load_library("broom")
load_library("eulerr")
load_library("dplyr")
load_library("knitr")
load_library("ggplot2")
load_library("ggmap")
load_library("tidyverse")
load_library("rnaturalearth")
load_library("parallel")
load_library("kableExtra")
load_library("mgcv")
load_library("ggmap")
load_library("ggrepel")
load_library("grid")
load_library("flextable")
load_library("yaml")
```


```{r widen data, include=FALSE}

# Indexes giving how serie ids relate to habitat type, restocking and ecoregions
subpop_fct <- d.cpue %>%
  select("ser_nameshort","ser_hty_code","ser_restocking","ecoregion") %>%
unique()

# add size of river to tested hypotheses
RS <- read.csv2("data/Silver_Series_RiverSize.csv")
RS <- RS %>% select(ser_namesh,SubjectiveSize)
subpop_fct <- subpop_fct %>% left_join(RS,by=join_by(ser_nameshort==ser_namesh))

# Wide format of silver eel data
S_data <- d.cpue %>%
  select("das_year","ser_nameshort","cpue") %>% 
  complete(das_year,ser_nameshort) %>% # add na´s to non existing years
pivot_wider(names_from=ser_nameshort,values_from = cpue) # wide format

# Rearrange data for fitting MARSS model
Years <- S_data$das_year
S_ts <- S_data[,names(S_data)!="das_year"]
S_ts <- t(S_ts) # transpose matrix
S_ts <- S_ts[subpop_fct$ser_nameshort,] # rearrange row order(same as subpop_fct)
#S_ts <- log(S_ts) # log data
#S_ts[is.infinite(S_ts)] <- -15

# z-score data
S_ts <- t(apply(S_ts, 1,function(df) (df-mean(df,na.rm=TRUE))/sd(df,na.rm=TRUE)))
n_series <- nrow(S_ts) # number of series

```


```{r Create MARSS model structure, silent=true}

# H1: panmictic population
Z1 <- factor(rep("pan", n_series))

# H2: Habitat type
Z2 <- factor(subpop_fct$ser_hty_code)

# H3: Restocking
Z3 <- factor(subpop_fct$ser_restocking)

# H4: Ecoregion
Z4 <- factor(subpop_fct$ecoregion)

# H5: North Sea vs. Elsewhere europe
Z5 <- factor(ifelse(subpop_fct$ecoregion %in% c("Greater North Sea"), "North Sea", "Elsewhere Europe"))

# H6: Catchment size
Z6 <- factor(subpop_fct$SubjectiveSize)

# all models
Z.models <- list(Z1, Z2, Z3, Z4, Z5, Z6)
names(Z.models) <-
c("panmictic", "Habitat type", "Restocking", "Ecoregion", "North Sea vs. elsewhere europe", "Catchment size")

# Model parameters(the same across  all models) 
U.model <- "unequal"
R.model <- "diagonal and unequal"
#A.model <- "zero"
B.model <- "identity"
Q.model <- c("diagonal and equal") # test with different Q models(i.e. different process errors)
x0.model <- "unequal"
V0.model <- "zero"
model.constant <- list(
U = U.model, R = R.model, Q = Q.model, # A = A.model,
x0 = x0.model, V0 = V0.model, tinitx = 0
)
A.models <- c("zero","unequal")

```

```{r Fit MARSS models, silent=TRUE}
out.tab <- NULL
fits <- list()
for(A.model in A.models){
for (i in 1:length(Z.models)) { 
fit.model <- c(list(Z = Z.models[[i]]), A = A.model, model.constant)
fit <- MARSS(S_ts,
model = fit.model,
silent = TRUE, control = list(maxit = 2000)
)
out <- data.frame(
H = names(Z.models)[i],
A = A.model,
logLik = fit$logLik, AICc = fit$AICc, num.param = fit$num.params,
m = length(unique(Z.models[[i]])),
num.iter = fit$numIter, converged = !fit$convergence,
stringsAsFactors = FALSE
)
out.tab <- rbind(out.tab, out)
fits <- c(fits, list(fit))
if (i == 1) next # one m for panmictic so only run 1 Q
}
}

```

```{r make table}
flextable(out.tab)
```

```{r best model}
best_model <- fits[[which.min(out.tab$AICc)]] 
```


```{r plot trends, silent=TRUE}
Xt <- predict(best_model,type="xtT",interval = "confidence")
Xt <- Xt$pred
Xt$t <- Years # add data on years
Xt <- Xt %>% 
  rename(Year=t, subpopulation=.rownames, xt=estimate)

# plot subpopulation trends
ggplot(Xt,aes(group=subpopulation, y=xt, x=Year,color=subpopulation)) + 
  geom_line() +
  geom_line(aes(y=`Lo 95`),linetype="dashed") +
  geom_line(aes(y=`Hi 95`),linetype="dashed") +
  facet_wrap(vars(subpopulation),ncol=length(unique(Xt$subpopulation)))
```

```{r Plot smoothed state, silent=TRUE}
Yt <- predict(best_model,type=c("ytt"),interval = "confidence", filtered=TRUE)
Yt <- Yt$pred
Yt$t <- Years
Yt <- Yt %>% rename(Year=t, site=.rownames, yt=estimate)
Yt <- Yt %>% left_join(subpop_fct,by=join_by(site==ser_nameshort))

# plot subpopulation trends
Yt_plot <- ggplot(Yt,aes(y=yt, x=Year, color=ser_hty_code)) + 
  geom_line() +
  geom_line(aes(y=`Lo 95`),linetype="dashed") +
  geom_line(aes(y=`Hi 95`),linetype="dashed") +
  geom_point(aes(y=y)) +
  facet_wrap(vars(site),scales="free_y")  

ggsave("0_series.pdf",Yt_plot)

```

```{r plot ecoregion model}
best_model <- fits[[4]]
Xt <- predict(best_model,type="xtT",interval = "confidence")
Xt <- Xt$pred
Xt$t <- Years # add data on years
Xt <- Xt %>% 
  rename(Year=t, subpopulation=.rownames, xt=estimate)

# plot subpopulation trends
ggplot(Xt,aes(group=subpopulation, y=xt, x=Year,color=subpopulation)) + 
  geom_line() +
  geom_line(aes(y=`Lo 95`),linetype="dashed") +
  geom_line(aes(y=`Hi 95`),linetype="dashed") +
  facet_wrap(vars(subpopulation),ncol=length(unique(Xt$subpopulation)))

```

