### Conclusion on yellow and silver eel time series

These analyses are strictly exploratory and enable us to test certain statistical methods and their limitations for analysing temporal series on silver eels abundance. Thus, results should be treated with caution. Several problems have been identified and these points need to be improved to interpret the outputs.

- More data should be collected in underrepresented ecoregions, especially in the Mediterranean.
- Abundance data are given in numbers or in weight. However giving the dimorphism (female being older, larger and heavier) and the environmental sex determism for Euro-pean eel, changes in abundance may be reflected differently in numbers or in weight. Mixing time series in both unity may be misleading.
- In the Baltic Sea, international trawl survey data has not been updated since 2011. These series should be made available for WGEEL, if they are still being collected. Additionally, freshwater silver eel series are needed from the Northern/Northeastern Baltic Sea.
- In the WGEEL data call, the data providers should consult the ReadMe-file especially regarding the fishing/sampling season. Additionally, the definition of the fishing/sampling season should be discussed in WKEELDATA and be based on available data.
- To have more series available for analyses, the conditions for accepting the series for analysis should be re-evaluated (quality, number of years needed, etc.). In addition, series that are marked as low quality should be re-evaluated. 
- A more detailed review of the statistical methods that can be used should also be carried out to identify new ones.

Although these analyses of silver eel time series are exploratory, they do give us a first step towards benchmarking and using these data to assess European eel stocks. They enabled us to identify the limitations of dataset and how we can improve future data collection.

### References