SELECT * FROM DATAWG.LANDINGS where EEL_EMU_NAMESHORT like '%_total%';
SELECT EEL_TYP_ID, EEL_YEAR, EEL_COU_CODE, sum(EEL_VALUE) as landings, COUNT(*) as nb
FROM DATAWG.LANDINGS where EEL_EMU_NAMESHORT not like '%_total%'
group by EEL_TYP_ID, EEL_YEAR, EEL_COU_CODE;