# general configuration for shiny
# 
# Authors: lbeaulaton Cedric
# FIRST THING : load maps_for_shiny.Rdata in your data/shapefiles/ git directory
#             : load files dataset.Rdata, glass_eel_yoy.Rdata, older.Rdata, statseries.Rdata
#             : generated by the recruitment.rnw script in you

###############################################################################
# debug notes for Cedric ....
#setwd("C:\\Users\\cedric.briand\\Documents\\GitHub\\WGEEL\\R\\shiny_data_visualisation\\shiny")
# A big dataset is stored there
#"C:\\workspace\\wgeeldata\\shp"
# Other dataset are there
#/wgeeldata/recruitment/2018/data
# they are not in version control, they will be dropped on the sharepoint
# they need to be copied to 
# WGEEL\data

#-----------------
# shiny libraries
#-----------------
load_package("shiny")
load_package("shinyWidgets")
load_package("shinydashboard")
load_package("shinyjs")
load_package("shinyBS")
load_package("leaflet")
load_package("DT")
load_package("plotly")
load_package("leaflet.extras")
#-----------------
# other libraries
#-----------------
load_package("readxl")
load_package("stringr")
load_package("reshape2")
load_package("tidyr") # unite cols in maps
load_package("rlang")
load_package("sp")
#load_package("pool")
#load_package("DBI")
load_package("RPostgreSQL")
load_package("dplyr")
load_package("RColorBrewer")
load_package("sqldf")
load_package("scales")
load_package('stringr') # text handling
#load_package("XLConnect") # for excel
load_package("ggplot2") # for excel
load_package("gridExtra")
load_package("colorspace")
load_package("ggrepel")
load_package("viridis")
# load functions ------------------------------------------------------------------------------------
options()
# retrieve reference tables needed
# the shiny is launched from shiny_data_integration/shiny thus we need the ../
jscode <- "shinyjs.closeWindow = function() { window.close(); }"
if(is.null(options()$sqldf.RPostgreSQL.user)) 
source("../../database_interaction/database_connection.R")
source("../../database_interaction/database_reference.R")
source("../../database_interaction/database_data.R")
source("../../database_interaction/database_precodata.R")
source("../../stock_assessment/preco_diagram.R")
source("graphs.R")
source("maps.R")

# loading datasets 

# this file is added to the ignore list, so ask for it in your own git before launching the app
load("../../../data/shapefiles/maps_for_shiny.Rdata") 
habitat_ref <- extract_ref("Habitat type")
lfs_code_base <- extract_ref("Life stage")
#lfs_code_base <- lfs_code_base[!lfs_code_base$lfs_code %in% c("OG","QG"),]
country_ref <- extract_ref("Country")
country_ref <- country_ref[order(country_ref$cou_order), ]
country_ref$cou_code <- factor(country_ref$cou_code, levels = country_ref$cou_code[order(country_ref$cou_order)], ordered = TRUE)

# Extract data from the database -------------------------------------------------------------------

landings = extract_data("Landings")
aquaculture = extract_data("Aquaculture")
release = extract_data("Release")

precodata = extract_precodata() # for tables

precodata_all = extract_data("PrecoData All") # for precodiagram




# save(landings, aquaculture, release, precodata, habitat_ref, lfs_code_base, country_ref,  file= "../../../data/dataset.Rdata")
# without connexion to a database use Rdata instead, ask to Cedric

# current year --------------------------------------------------------------------------------------

CY = as.numeric(format(Sys.time(), "%Y"))

# load data from recruitment ------------------------------------------------------------------------
# note : these data have been produced by the script recruitment_analysis.Rnw
#      : they must be installed manually in folder /data  as we don't store data
#      : in git.
load("../../../data/wger.Rdata")
load("../../../data/wger_init.Rdata") # before selection process
load("../../../data/statseries.Rdata")
load("../../../data/glass_eel_yoy.Rdata")
load("../../../data/older.Rdata")
load("../../../data/R_stations.Rdata")
load("../../../data/dat_ge.Rdata") ; dat_ge <- dat
dat_ge$year <- as.numeric(format(dat_ge$year,"%Y"))
colnames(dat_ge)[colnames(dat_ge)=="p_std_1960_1979"] <- "geomean_p_std_1960_1979"
load("../../../data/dat_ye.Rdata") ; # named dat_ye
dat_ye$year <- as.numeric(dat_ye$year)
load("../../../data/glass_eel_pred.Rdata") # named glass_eel_pred
load("../../../data/yellow_eel_pred.Rdata") # named yellow_eel_pred
load("../../../data/recruitment_models.Rdata") # named model_ge_area and model_older
   
#########################
# functions -----------------------------------------------------------------------------------------
########################

# filter_data ---------------------------------------------------------------------------------------

#' @title Filtering function
#' @description This will filter according to user choice
#' @param dataset A character value, one of 'landings', 'aquaculture', 'stocking', 'precodata' pre 
#' loaded in the app
#' @param typ The type of data, 4 or 6, shiny returns a character.
#' @param life_stage The life stage, Default: NULL
#' @param country The country, Default: NULL
#' @param habitat The habitat, one of c("MO", "C", "T", "F", "AL", "NA"), Default: NULL
#' @param year_range A vector of years, Default: 1900:2100
#' @return filtered dataset
#' @details In a previous version the selection was done using a generated expression contraining all
#' elements of the argument (for instance if country=NULL then country=country_ref$cou_code), to generate
#' all possible levels. In the new, more complicated version when NULL is passed then the argument is ignored
#' if not null then we pass a list of quosures which is spliced using !!!
#' @examples 
#' \dontrun{
#' filter_data(dataset='landings',life_stage = NULL, country = NULL, habitat=NULL, year_range=2010:2018)
#' filter_data(dataset='landings',typ= 6 ,life_stage = NULL, country = NULL, habitat=NULL, 
#' year_range=2010:2018)
#' filter_data(dataset = "precodata",life_stage = NULL, country = levels(country_ref$cou_code),
#' year_range=2000:2018) 
#' }
#' @seealso 
#'  \code{\link[dplyr]{filter}}
#' @rdname filter_data
#' @importFrom dplyr filter
filter_data = function(dataset, typ=NULL, life_stage = NULL, country = NULL, habitat=NULL, 
    year_range = 1900:2100)
{
  mydata <- get(dataset)

  # this is the list of quosures
  expr <- list()
  # year is always passed
  expr[[1]] <- rlang::quo(eel_year %in% year_range)
  # country is passed if not null, if NULL then the dataset will not be filtered
  i=2
  if (!is.null(country)) {
    expr[[i]]=rlang::quo(eel_cou_code %in% country) 
    i=i+1
  }  
  if (!is.null(life_stage)) {
    expr[[i]]=rlang::quo(eel_lfs_code%in%life_stage) 
    i=i+1
  }   
  if (!is.null(habitat) & dataset != "precodata") {
    # NA will be displayed as a data type, they are included in the shiny list of possible choices
    mydata$eel_hty_code[is.na(mydata$eel_hty_code)]<-"NA"
    expr[[i]]=rlang::quo(eel_hty_code %in% habitat) 
    i=i+1
  } 
  if (!is.null(typ)& dataset != "precodata") {
    expr[[i]]=rlang::quo(eel_typ_id%in% typ) 
    i=i+1
  }   
    
  # !!! takes a list of elements and splices them into to the current call
	filtered_data = mydata%>%dplyr::filter(!!!expr)
    # this will retain all levels for graph
    # filtered_data$eel_hty_code = factor(filtered_data$eel_hty_code, 
    # levels = rev(c("MO", "C", "T", "F", "AL", "NA")))
  
  return(filtered_data)
}
#filter_precodata filtre pour créer les jeux de données pour la table et le graphe de preco

filter_precodata = function(dataset, country=NULL, habitat=NULL,lfs=NULL, year_range = 1900:2100){
  mydata <- get(dataset)
  
  if(!is.null(lfs)){
    
    if (!is.null(country) & !is.null(habitat)){
      filtered_data<-subset(mydata, eel_cou_code %in% country & eel_lfs_code %in% lfs & eel_year %in% year_range & eel_hty_code %in% habitat)
      
    }
    
    if (!is.null(country) & is.null(habitat)){ 
      filtered_data<-subset(mydata, eel_cou_code %in% country & eel_lfs_code %in% lfs & eel_year %in% year_range)
      
    }
    
    if (!is.null(habitat) & is.null(country)){
      filtered_data<-subset(mydata, eel_year %in% year_range & eel_lfs_code %in% lfs & eel_hty_code %in% habitat)
      #filtered_data <-aggregate(selection, by=list(selection$eel_year, selection$eel_cou_code),
      #  FUN=mean, na.rm=TRUE)
    }
    if (is.null(country) & is.null(habitat)){
      
      filtered_data<-subset(mydata, eel_year %in% year_range & eel_lfs_code %in% lfs)
      
    }
  }else{
    if (!is.null(country) & !is.null(habitat)){
      filtered_data<-subset(mydata, eel_cou_code %in% country & eel_year %in% year_range & eel_hty_code %in% habitat)
      
    }
    
    if (!is.null(country) & is.null(habitat)){ 
      filtered_data<-subset(mydata, eel_cou_code %in% country & eel_year %in% year_range)
      
    }
    
    if (!is.null(habitat) & is.null(country)){
      filtered_data<-subset(mydata, eel_year %in% year_range & eel_hty_code %in% habitat)

    }
    if (is.null(country) & is.null(habitat)){
      
      filtered_data<-subset(mydata, eel_year %in% year_range)
      
    }    
    
  }

return(filtered_data)  
}

### an aggregate function for the precodata

agg_precodata<-function(dataset,geo="country",country=NULL,habitat=NULL, year_range = 1900:2100){
 
   dataset2<-data.frame(dataset,sumht=dataset$sumh*dataset$bbest,sumat=dataset$suma*dataset$bbest,sumft=dataset$sumf*dataset$bbest)
  
   if(!is.null(habitat)){
	   if (geo=="country"){
		   agg_data<-dataset2 %>% 
				   group_by(eel_cou_code,eel_year) %>% 
				   summarise(bcurrent = sum(bcurrent), bbest = sum(bbest), b0 = sum(b0) , 
						   sumA = sum(sumat)/sum(bbest, na.rm=T),sumF = sum(sumft)/sum(bbest, na.rm=T), 
						   sumH=sum(sumht)/sum(bbest, na.rm=T))
	   } else {
		   agg_data<-dataset2 %>% 
				   group_by(eel_emu_nameshort,eel_year) %>% 
				   summarise(bcurrent = sum(bcurrent), bbest = sum(bbest), b0 = sum(b0), 
						   sumA = sum(sumat)/sum(bbest, na.rm=T),sumF = sum(sumft)/sum(bbest, na.rm=T), 
						   sumH=sum(sumht)/sum(bbest, na.rm=T))
	   }
   } else {
	   if (geo=="country"){
		   agg_data<-dataset2 %>% 
				   group_by(eel_cou_code,eel_year,eel_hty_code) %>% 
				   summarise(bcurrent = sum(bcurrent), bbest = sum(bbest), b0 = sum(b0) , 
						   sumA = sum(sumat)/sum(bbest, na.rm=T),sumF = sum(sumft)/sum(bbest, na.rm=T), 
						   sumH=sum(sumht)/sum(bbest, na.rm=T))
	   } else {
		   agg_data<-dataset2 %>% 
				   group_by(eel_emu_nameshort,eel_year,eel_hty_code) %>% 
				   summarise(bcurrent = sum(bcurrent), bbest = sum(bbest), b0 = sum(b0) , 
						   sumA = sum(sumat)/sum(bbest, na.rm=T),sumF = sum(sumft)/sum(bbest, na.rm=T), 
						   sumH=sum(sumht)/sum(bbest, na.rm=T))
	   }   
   } 


  return(agg_data)
}
##

# group_data ----------------------------------------------------------------------------------------

#' @title function to group data
#' @description Data are grouped in the simplest way (year, country) or also by habitat or life stage, 
#' the grouping can be by emu or country
#' @param dataset the data
#' @param geo One of 'country' or 'emu', Default: 'country'
#' @param habitat Do you want result split per habitat, Default: FALSE
#' @param lfs Do you want results split by life stage, Default: FALSE
#' @return A grouped dataset
#' @details ...
#' @examples 
#' \dontrun{  
#'  filtered_data <- filter_data(dataset='landings',life_stage = NULL, country = NULL, habitat=NULL, year_range=1960:2011)
#'  grouped_data <- group_data(filtered_data, geo="country", habitat=FALSE, lfs=FALSE)
#' }
#' @seealso 
#'  \code{\link[dplyr]{group_by}}
#' @rdname group_data
#' @importFrom dplyr group_by
group_data <- function(dataset, geo="country", habitat=FALSE, lfs=FALSE, na.rm = TRUE){
  if (!geo %in% c("country","emu")) stop ("geo should be country or emu")
  if (habitat & lfs){
    # filtered by habitat and lfs
    if (geo=="country") {
      # by country
      dataset <- dataset %>%
          dplyr::group_by(eel_cou_code,eel_year,eel_hty_code,eel_lfs_code) %>%
	      summarize(eel_value=sum(eel_value,na.rm=na.rm))
    } else {
      # by emu
      dataset <- dataset %>%
          dplyr::group_by(eel_emu_nameshort,eel_year,eel_hty_code,eel_lfs_code) %>%
	      summarize(eel_value=sum(eel_value,na.rm=na.rm))
      
    }
    
  } else if (habitat){ 
    # filtered by habitat and lfs
    if (geo=="country") {
      # by country
      dataset <- dataset %>%
          dplyr::group_by(eel_cou_code,eel_year,eel_hty_code) %>%
	      summarize(eel_value=sum(eel_value,na.rm=na.rm))
    } else {
      # by emu
      dataset <- dataset %>%
          dplyr::group_by(eel_emu_nameshort,eel_year,eel_hty_code) %>%
	      summarize(eel_value=sum(eel_value,na.rm=na.rm))
    }
    
  } else if (lfs) {
    # filtered by habitat and lfs
    if (geo=="country") {
      # by country
      dataset <- dataset %>%
          dplyr::group_by(eel_cou_code,eel_year,eel_lfs_code) %>%
	      summarize(eel_value=sum(eel_value,na.rm=na.rm))
    } else {
      # by emu
      dataset <- dataset %>%
          dplyr::group_by(eel_emu_nameshort,eel_year,eel_lfs_code) %>%
	      summarize(eel_value=sum(eel_value,na.rm=na.rm))
    }    
    
  } else {
    # not filtered by habitat nor lfs
    if (geo=="country") {
      # by country
      dataset <- dataset %>%
          dplyr::group_by(eel_cou_code,eel_year) %>%
	      summarize(eel_value=sum(eel_value,na.rm=na.rm))
    } else {
      # by emu
      dataset <- dataset %>%
          dplyr::group_by(eel_emu_nameshort,eel_year) %>%
	      summarize(eel_value=sum(eel_value,na.rm=na.rm))
      
    }
  }
  return(dataset)
}  

# predict_missing_values ----------------------------------------------------------------------------

#TODO swith to gam for years.... issue #40
#' @title Predict missing values for landings
#' @description Use simple glm with factors year and countries to make predictions
#' @param landings The dataset of landings
#' @return Landings with missing values filled with predictions
#' @details Use a loop not very efficient
#' @examples 
#' \dontrun{
#' landings <-group_data(filtered_data,geo="country",habitat=FALSE,lfs=FALSE)
#' landings$eel_value <- as.numeric(landings$eel_value) / 1000
#' landings$eel_cou_code = as.factor(landings$eel_cou_code)                       
#' pred_landings <- predict_missing_values(landings, verbose=TRUE) 
#' }
#' @rdname predict_missing_values
#' @export 
predict_missing_values <- function(landings, verbose=FALSE, na.rm=FALSE){
  landings <-as.data.frame(landings)
  landings$lvalue<-log(landings$eel_value+0.001) #introduce +0.001 to use 0 data
  landings$eel_year<-as.factor(landings$eel_year)
  landings$eel_cou_code <- as.factor(as.character(landings$eel_cou_code))
  glm_la<-glm(lvalue~ eel_year + eel_cou_code, data=landings )
  if (verbose)  print(summary(glm_la)) # check fit
  landings2<-expand.grid("eel_year"=glm_la$xlevels$eel_year,"eel_cou_code"=glm_la$xlevels$eel_cou_code)
  landings2$pred=predict(glm_la,newdat=landings2,type="response")
  # BELOW WE REPLACE MISSING VALUES BY THE PREDICTED MODELLED
  value_to_test = numeric(0)
  
  for (y in unique(landings$eel_year)){
    for (c in levels(landings$eel_cou_code)){
      if (identical(landings[landings$eel_year==y&landings$eel_cou_code==c,"eel_value"],value_to_test)){ 
        # no data ==> replace by predicted
        landings2[landings2$eel_year == y & landings2$eel_cou_code == c,"eel_value"]<-round(exp(landings2[landings2$eel_year==y&landings2$eel_cou_code==c,"pred"]))
        landings2[landings2$eel_year == y & landings2$eel_cou_code == c,"predicted"]<-TRUE
      } else {
        # use actual value

        landings2[landings2$eel_year == y & landings2$eel_cou_code == c,"eel_value"]<-round(landings[landings$eel_year==y&landings$eel_cou_code==c,"eel_value"])
        landings2[landings2$eel_year == y & landings2$eel_cou_code == c,"predicted"]<-FALSE
      }
    }
  }
  landings2$eel_year<-as.numeric(as.character(landings2$eel_year))  
  return(landings2)  
}

# Color palettes ------------------------------------------------------------------------------------

#TODO create better colors

values=c(RColorBrewer::brewer.pal(12,"Set3"),
    RColorBrewer::brewer.pal(12, "Paired"), 
    RColorBrewer::brewer.pal(8,"Accent"),
    RColorBrewer::brewer.pal(8, "Dark2"))
color_countries = setNames(values,country_ref$cou_code)




